# Auto-generated by shared/proto/scripts/fix_python_init.py — DO NOT EDIT MANUALLY.
# Re-exports all betterproto-generated models so consumers can use:
#   from dronefleet_shared.models import Drone, DroneStatus, ...
from .dronefleet.v1 import (
    ActionType,
    Depot,
    Drone,
    DroneStatus,
    DroneTelemetry,
    Mission,
    MissionAssignment,
    OptimizationSnapshot,
    Order,
    OrderPriority,
    OrderStatus,
    Position,
    ProductType,
    Warehouse,
    Waypoint,
    WaypointType,
)

__all__ = [
    "ActionType",
    "Depot",
    "Drone",
    "DroneStatus",
    "DroneTelemetry",
    "Mission",
    "MissionAssignment",
    "OptimizationSnapshot",
    "Order",
    "OrderPriority",
    "OrderStatus",
    "Position",
    "ProductType",
    "Warehouse",
    "Waypoint",
    "WaypointType",
]
