[tools]
# --- Python Backend (Ingestion & Optimizer) ---
python = "3.11"
uv = "0.5.11"

# --- Java Backend (State Manager) ---
java = "temurin-21"  # Java 21 LTS (Eclipse Temurin Distribution)
# gradle = "8.5"       # Use ./gradlew in the state-manager folder

# --- Infrastructure & Cloud ---
terraform = "1.9.0"
gcloud = "latest"

# --- Utility Tools ---
jq = "1.7.1"

[env]
# Auto-loaded when you entering the folder

# PROJECT_STRATEGY: on_cloud or on_premise
PROJECT_STRATEGY = "on_cloud"

# ENVIRONMENT: dev, preprod, prod
ENVIRONMENT = "dev"

# PROJECT_ID: Google Cloud project ID
PROJECT_ID = "drone-project-dev"
PUBSUB_EMULATOR_HOST = "localhost:8085"

# Add src to PYTHONPATH so python can find 'shared' modules
PYTHONPATH = "src"

# Instructs Python to use virtual environments in the .venv folder
UV_PROJECT_ENVIRONMENT = ".venv"

[tasks]
# Initialize project dependencies
"project:init" = "uv venv"
"project:activate-env" = "uv sync"

# Start docker containers
"docker:up" = "docker compose -f infrastructure/on_premise/docker-compose.yml up -d"
"docker:down" = "docker compose -f infrastructure/on_premise/docker-compose.yml down"

# Run ingestion and optimizer
"run:ingestion" = "uv run fastapi dev src/ingestion-api/main.py"
"run:optimizer" = "uv run python src/optimizer-engine/solver/main.py"
"run:simulator" = "uv run python src/simulator/main.py"

# Run linting
"lint:python" = "uv lint"
"lint:java" = "cd src/state-manager && ./gradlew checkstyleMain"
"lint:terraform" = "terraform fmt -recursive"
"lint:docker" = "docker compose lint"
"lint:all" = "lint:python && lint:java && lint:terraform && lint:docker"

# Run tests
"test:unit" = "uv run pytest"
"test:integration" = "uv run pytest --integration"
"test:e2e" = "uv run pytest --e2e"