[project]
name = "ingestion"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "dronefleet-messaging",
  "dronefleet-shared",
  "fastapi[standard]>=0.126.0",
  "google-cloud-pubsub>=2.33.0",
  "kafka-python>=2.3.0",
  "uvicorn>=0.38.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
dronefleet-shared = { workspace = true }
dronefleet-messaging = { workspace = true }
