#!/usr/bin/env python3
"""Post-generate script: rebuild models/__init__.py with re-exports from betterproto output.

betterproto generates all Python models into models/dronefleet/v1.py but leaves
models/__init__.py empty.  Consumers throughout the codebase import from
`dronefleet_shared.models` directly (e.g. `from dronefleet_shared.models import Drone`),
so __init__.py must re-export every public symbol from dronefleet.v1.

This script extracts all top-level class names from v1.py and writes the
re-export file automatically — no manual update needed when new proto messages
or enums are added.

Usage:
    python shared/proto/scripts/fix_python_init.py
    # or from shared/proto/:
    python scripts/fix_python_init.py
"""

import re
import sys
from pathlib import Path

# Resolve paths relative to this script's location (shared/proto/scripts/)
SCRIPT_DIR = Path(__file__).resolve().parent
MODELS_DIR = (
    SCRIPT_DIR.parent.parent / "python" / "src" / "dronefleet_shared" / "models"
)
V1_FILE = MODELS_DIR / "dronefleet" / "v1.py"
INIT_FILE = MODELS_DIR / "__init__.py"

# Regex to match top-level class definitions (enums + dataclasses)
CLASS_RE = re.compile(r"^class\s+(\w+)\s*\(", re.MULTILINE)


def extract_class_names(v1_path: Path) -> list[str]:
    """Extract all top-level class names from the betterproto-generated v1.py."""
    if not v1_path.exists():
        print(f"ERROR: {v1_path} not found. Run 'buf generate' first.", file=sys.stderr)
        sys.exit(1)

    source = v1_path.read_text()
    names = CLASS_RE.findall(source)

    if not names:
        print(f"WARNING: No classes found in {v1_path}", file=sys.stderr)
        sys.exit(1)

    return sorted(names)


def generate_init(class_names: list[str]) -> str:
    """Generate the __init__.py content with re-exports."""
    imports = ",\n    ".join(class_names)
    all_items = ",\n    ".join(f'"{n}"' for n in class_names)

    return f"""\
# Auto-generated by shared/proto/scripts/fix_python_init.py — DO NOT EDIT MANUALLY.
# Re-exports all betterproto-generated models so consumers can use:
#   from dronefleet_shared.models import Drone, DroneStatus, ...
from .dronefleet.v1 import (
    {imports},
)

__all__ = [
    {all_items},
]
"""


def main() -> None:
    class_names = extract_class_names(V1_FILE)
    content = generate_init(class_names)
    INIT_FILE.write_text(content)
    print(
        f"OK: wrote {len(class_names)} re-exports to {INIT_FILE.relative_to(SCRIPT_DIR.parent.parent.parent)}"
    )


if __name__ == "__main__":
    main()
