spring:
  # Disable Docker Compose auto-startup (we use GCP emulators manually)
  docker:
    compose:
      enabled: false

  cloud:
    gcp:
      project-id: ${PROJECT_ID:drone-fleet-optimizer-local}

      # Pub/Sub Emulator
      pubsub:
        emulator-host: ${PUBSUB_EMULATOR_HOST:localhost:8085}
        subscriber:
          parallel-pull-count: 10 # number of messages to pull in parallel from one topic
          executor-threads: 20 # number of threads pools to use for the executor

      # Firestore Emulator
      firestore:
        host-port: ${FIRESTORE_EMULATOR_HOST:localhost:8080}
        project-id: ${PROJECT_ID:drone-fleet-optimizer-local}
        enabled: true

      # For local emulation, we can bypass credential check by setting this
      credentials:
        # Base64 for {"account": "fake", "type": "service_account"} to make the emualtor work
        encoded-key: "eyJhY2NvdW50IjogImZha2UiLCAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQifQ==" # pragma: allowlist secret

# Topics Pub/Sub
pubsub:
  topics:
    telemetry: ${PUBSUB_TOPIC_TELEMETRY:telemetry}
    orders: ${PUBSUB_TOPIC_ORDERS:orders}
    commands: ${PUBSUB_TOPIC_COMMANDS:commands}
  subscriptions:
    telemetry: ${PUBSUB_TOPIC_TELEMETRY:telemetry}-sub
    orders: ${PUBSUB_TOPIC_ORDERS:orders}-sub
    commands: ${PUBSUB_TOPIC_COMMANDS:commands}-sub

# Logging verbose en local
logging:
  level:
    '[com.dronefleet.statemanager]': DEBUG
