spring:
  cloud:
    gcp:
      project-id: ${PROJECT_ID:drone-fleet-dev}

      pubsub:
        subscriber:
          parallel-pull-count: 50
          executor-threads: 100

# Topics Pub/Sub (créés par Terraform)
pubsub:
  topics:
    telemetry: ${PUBSUB_TOPIC_TELEMETRY:telemetry}
    orders: ${PUBSUB_TOPIC_ORDERS:orders}
    commands: ${PUBSUB_TOPIC_COMMANDS:commands}
  subscriptions:
    telemetry: ${PUBSUB_TOPIC_TELEMETRY:telemetry}-sub
    orders: ${PUBSUB_TOPIC_ORDERS:orders}-sub
    commands: ${PUBSUB_TOPIC_COMMANDS:commands}-sub

logging:
  level:
    com.dronefleet.statemanager: DEBUG
