services:

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=drone-project-dev --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    networks:
      - drone-network

  ingestion-api:
    build:
      context: ./src/ingestion-api
      dockerfile: Dockerfile
    environment:
      # LA VARIABLE MAGIQUE :
      # Le SDK Google vérifie cette variable. Si elle existe, il ignore la vraie auth GCP
      # et parle à l'émulateur. Pas besoin de changer ton code !
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
      PUBSUB_PROJECT_ID: drone-project-dev
    depends_on:
      - pubsub-emulator
    ports:
      - "8000:8000"
    networks:
      - drone-network

  state-manager:
    build:
      context: ./src/state-manager
      dockerfile: Dockerfile
    environment:
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
      SPRING_CLOUD_GCP_PROJECT_ID: drone-project-dev
    depends_on:
      - pubsub-emulator
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge