# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dronefleet/v1/common.proto, dronefleet/v1/depot.proto, dronefleet/v1/drone.proto, dronefleet/v1/mission.proto, dronefleet/v1/order.proto, dronefleet/v1/warehouse.proto, dronefleet/v1/snapshot.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto


class DroneStatus(betterproto.Enum):
    DRONE_STATUS_UNSPECIFIED = 0
    DRONE_STATUS_IDLE = 1
    DRONE_STATUS_RESERVED = 2
    DRONE_STATUS_MOVING = 3
    DRONE_STATUS_DELIVERING = 4
    DRONE_STATUS_CHARGING = 5
    DRONE_STATUS_MAINTENANCE = 6
    DRONE_STATUS_PROBLEM = 7
    DRONE_STATUS_EMERGENCY = 8
    DRONE_STATUS_UNKNOWN = 9


class OrderStatus(betterproto.Enum):
    ORDER_STATUS_UNSPECIFIED = 0
    ORDER_STATUS_PENDING = 1
    ORDER_STATUS_SOLVING = 2
    ORDER_STATUS_ASSIGNED = 3
    ORDER_STATUS_IN_DELIVERY = 4
    ORDER_STATUS_DELIVERED = 5
    ORDER_STATUS_CANCELLED = 6


class OrderPriority(betterproto.Enum):
    ORDER_PRIORITY_UNSPECIFIED = 0
    ORDER_PRIORITY_STANDARD = 1
    ORDER_PRIORITY_HIGH = 2
    ORDER_PRIORITY_CRITICAL = 3


class ProductType(betterproto.Enum):
    PRODUCT_TYPE_UNSPECIFIED = 0
    PRODUCT_TYPE_MEDICINE = 1
    PRODUCT_TYPE_VACCINE = 2
    PRODUCT_TYPE_BLOOD = 3
    PRODUCT_TYPE_ORGAN = 4
    PRODUCT_TYPE_MEDICAL_DEVICE = 5


class ActionType(betterproto.Enum):
    ACTION_TYPE_UNSPECIFIED = 0
    ACTION_TYPE_FLY_TO = 1
    ACTION_TYPE_PICKUP = 2
    ACTION_TYPE_DROPOFF = 3
    ACTION_TYPE_CHARGE = 4


class WaypointType(betterproto.Enum):
    WAYPOINT_TYPE_UNSPECIFIED = 0
    WAYPOINT_TYPE_DEPOT_START = 1
    WAYPOINT_TYPE_WAREHOUSE_PICKUP = 2
    WAYPOINT_TYPE_HOSPITAL_DELIVERY = 3
    WAYPOINT_TYPE_DEPOT_RETURN = 4


@dataclass
class Position(betterproto.Message):
    lat: float = betterproto.double_field(1)
    lon: float = betterproto.double_field(2)


@dataclass
class Depot(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    position: "Position" = betterproto.message_field(3)
    capacity: int = betterproto.int32_field(4)
    charging_slots: int = betterproto.int32_field(5)


@dataclass
class Drone(betterproto.Message):
    id: str = betterproto.string_field(1)
    position: "Position" = betterproto.message_field(2)
    battery_percentage: float = betterproto.double_field(3)
    speed_kmh: float = betterproto.double_field(4)
    status: "DroneStatus" = betterproto.enum_field(5)
    current_mission_id: str = betterproto.string_field(6)
    last_update: datetime = betterproto.message_field(7)
    solving_session_id: str = betterproto.string_field(8)
    home_depot_id: str = betterproto.string_field(9)
    battery_capacity_mah: int = betterproto.int32_field(10)
    consumption_per_km: float = betterproto.double_field(11)
    max_flight_time_minutes: int = betterproto.int32_field(12)
    short_name: str = betterproto.string_field(13)


@dataclass
class DroneTelemetry(betterproto.Message):
    drone_id: str = betterproto.string_field(1)
    timestamp: datetime = betterproto.message_field(2)
    position: "Position" = betterproto.message_field(3)
    battery_percentage: float = betterproto.double_field(4)
    speed_kmh: float = betterproto.double_field(5)
    status: "DroneStatus" = betterproto.enum_field(6)
    current_mission_id: str = betterproto.string_field(7)


@dataclass
class Waypoint(betterproto.Message):
    type: "WaypointType" = betterproto.enum_field(1)
    position: "Position" = betterproto.message_field(2)
    related_order_id: str = betterproto.string_field(3)
    related_warehouse_id: str = betterproto.string_field(4)


@dataclass
class Mission(betterproto.Message):
    id: str = betterproto.string_field(1)
    drone_id: str = betterproto.string_field(2)
    order_ids: List[str] = betterproto.string_field(3)
    route: List["Waypoint"] = betterproto.message_field(4)
    status: str = betterproto.string_field(5)
    start_time: datetime = betterproto.message_field(6)
    end_time: datetime = betterproto.message_field(7)
    estimated_battery_consumption: float = betterproto.double_field(8)
    estimated_duration_minutes: float = betterproto.double_field(9)


@dataclass
class MissionAssignment(betterproto.Message):
    drone_id: str = betterproto.string_field(1)
    order_ids: List[str] = betterproto.string_field(2)
    route: List["Waypoint"] = betterproto.message_field(3)
    estimated_battery_consumption: float = betterproto.double_field(4)
    estimated_duration_minutes: float = betterproto.double_field(5)


@dataclass
class Order(betterproto.Message):
    id: str = betterproto.string_field(1)
    pickup_location: "Position" = betterproto.message_field(2)
    delivery_location: "Position" = betterproto.message_field(3)
    status: "OrderStatus" = betterproto.enum_field(4)
    priority: "OrderPriority" = betterproto.enum_field(5)
    product_type: str = betterproto.string_field(6)
    created_at: datetime = betterproto.message_field(7)
    assigned_drone_id: str = betterproto.string_field(8)
    assigned_mission_id: str = betterproto.string_field(9)
    solving_session_id: str = betterproto.string_field(10)


@dataclass
class Warehouse(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    position: "Position" = betterproto.message_field(3)
    authorized_product_types: List[str] = betterproto.string_field(4)
    is_cold_storage_capable: bool = betterproto.bool_field(5)


@dataclass
class OptimizationSnapshot(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    timestamp: datetime = betterproto.message_field(2)
    depot: "Depot" = betterproto.message_field(3)
    drones: List["Drone"] = betterproto.message_field(4)
    orders: List["Order"] = betterproto.message_field(5)
    warehouses: List["Warehouse"] = betterproto.message_field(6)
