// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: dronefleet/v1/common.proto

/* eslint-disable */

export const protobufPackage = "dronefleet.v1";

export enum DroneStatus {
  DRONE_STATUS_UNSPECIFIED = 0,
  DRONE_STATUS_IDLE = 1,
  DRONE_STATUS_RESERVED = 2,
  DRONE_STATUS_MOVING = 3,
  DRONE_STATUS_DELIVERING = 4,
  DRONE_STATUS_CHARGING = 5,
  DRONE_STATUS_MAINTENANCE = 6,
  DRONE_STATUS_PROBLEM = 7,
  DRONE_STATUS_EMERGENCY = 8,
  DRONE_STATUS_UNKNOWN = 9,
  UNRECOGNIZED = -1,
}

export function droneStatusFromJSON(object: any): DroneStatus {
  switch (object) {
    case 0:
    case "DRONE_STATUS_UNSPECIFIED":
      return DroneStatus.DRONE_STATUS_UNSPECIFIED;
    case 1:
    case "DRONE_STATUS_IDLE":
      return DroneStatus.DRONE_STATUS_IDLE;
    case 2:
    case "DRONE_STATUS_RESERVED":
      return DroneStatus.DRONE_STATUS_RESERVED;
    case 3:
    case "DRONE_STATUS_MOVING":
      return DroneStatus.DRONE_STATUS_MOVING;
    case 4:
    case "DRONE_STATUS_DELIVERING":
      return DroneStatus.DRONE_STATUS_DELIVERING;
    case 5:
    case "DRONE_STATUS_CHARGING":
      return DroneStatus.DRONE_STATUS_CHARGING;
    case 6:
    case "DRONE_STATUS_MAINTENANCE":
      return DroneStatus.DRONE_STATUS_MAINTENANCE;
    case 7:
    case "DRONE_STATUS_PROBLEM":
      return DroneStatus.DRONE_STATUS_PROBLEM;
    case 8:
    case "DRONE_STATUS_EMERGENCY":
      return DroneStatus.DRONE_STATUS_EMERGENCY;
    case 9:
    case "DRONE_STATUS_UNKNOWN":
      return DroneStatus.DRONE_STATUS_UNKNOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DroneStatus.UNRECOGNIZED;
  }
}

export function droneStatusToJSON(object: DroneStatus): string {
  switch (object) {
    case DroneStatus.DRONE_STATUS_UNSPECIFIED:
      return "DRONE_STATUS_UNSPECIFIED";
    case DroneStatus.DRONE_STATUS_IDLE:
      return "DRONE_STATUS_IDLE";
    case DroneStatus.DRONE_STATUS_RESERVED:
      return "DRONE_STATUS_RESERVED";
    case DroneStatus.DRONE_STATUS_MOVING:
      return "DRONE_STATUS_MOVING";
    case DroneStatus.DRONE_STATUS_DELIVERING:
      return "DRONE_STATUS_DELIVERING";
    case DroneStatus.DRONE_STATUS_CHARGING:
      return "DRONE_STATUS_CHARGING";
    case DroneStatus.DRONE_STATUS_MAINTENANCE:
      return "DRONE_STATUS_MAINTENANCE";
    case DroneStatus.DRONE_STATUS_PROBLEM:
      return "DRONE_STATUS_PROBLEM";
    case DroneStatus.DRONE_STATUS_EMERGENCY:
      return "DRONE_STATUS_EMERGENCY";
    case DroneStatus.DRONE_STATUS_UNKNOWN:
      return "DRONE_STATUS_UNKNOWN";
    case DroneStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  ORDER_STATUS_PENDING = 1,
  ORDER_STATUS_SOLVING = 2,
  ORDER_STATUS_ASSIGNED = 3,
  ORDER_STATUS_IN_DELIVERY = 4,
  ORDER_STATUS_DELIVERED = 5,
  ORDER_STATUS_CANCELLED = 6,
  UNRECOGNIZED = -1,
}

export function orderStatusFromJSON(object: any): OrderStatus {
  switch (object) {
    case 0:
    case "ORDER_STATUS_UNSPECIFIED":
      return OrderStatus.ORDER_STATUS_UNSPECIFIED;
    case 1:
    case "ORDER_STATUS_PENDING":
      return OrderStatus.ORDER_STATUS_PENDING;
    case 2:
    case "ORDER_STATUS_SOLVING":
      return OrderStatus.ORDER_STATUS_SOLVING;
    case 3:
    case "ORDER_STATUS_ASSIGNED":
      return OrderStatus.ORDER_STATUS_ASSIGNED;
    case 4:
    case "ORDER_STATUS_IN_DELIVERY":
      return OrderStatus.ORDER_STATUS_IN_DELIVERY;
    case 5:
    case "ORDER_STATUS_DELIVERED":
      return OrderStatus.ORDER_STATUS_DELIVERED;
    case 6:
    case "ORDER_STATUS_CANCELLED":
      return OrderStatus.ORDER_STATUS_CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStatus.UNRECOGNIZED;
  }
}

export function orderStatusToJSON(object: OrderStatus): string {
  switch (object) {
    case OrderStatus.ORDER_STATUS_UNSPECIFIED:
      return "ORDER_STATUS_UNSPECIFIED";
    case OrderStatus.ORDER_STATUS_PENDING:
      return "ORDER_STATUS_PENDING";
    case OrderStatus.ORDER_STATUS_SOLVING:
      return "ORDER_STATUS_SOLVING";
    case OrderStatus.ORDER_STATUS_ASSIGNED:
      return "ORDER_STATUS_ASSIGNED";
    case OrderStatus.ORDER_STATUS_IN_DELIVERY:
      return "ORDER_STATUS_IN_DELIVERY";
    case OrderStatus.ORDER_STATUS_DELIVERED:
      return "ORDER_STATUS_DELIVERED";
    case OrderStatus.ORDER_STATUS_CANCELLED:
      return "ORDER_STATUS_CANCELLED";
    case OrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderPriority {
  ORDER_PRIORITY_UNSPECIFIED = 0,
  ORDER_PRIORITY_STANDARD = 1,
  ORDER_PRIORITY_HIGH = 2,
  ORDER_PRIORITY_CRITICAL = 3,
  UNRECOGNIZED = -1,
}

export function orderPriorityFromJSON(object: any): OrderPriority {
  switch (object) {
    case 0:
    case "ORDER_PRIORITY_UNSPECIFIED":
      return OrderPriority.ORDER_PRIORITY_UNSPECIFIED;
    case 1:
    case "ORDER_PRIORITY_STANDARD":
      return OrderPriority.ORDER_PRIORITY_STANDARD;
    case 2:
    case "ORDER_PRIORITY_HIGH":
      return OrderPriority.ORDER_PRIORITY_HIGH;
    case 3:
    case "ORDER_PRIORITY_CRITICAL":
      return OrderPriority.ORDER_PRIORITY_CRITICAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderPriority.UNRECOGNIZED;
  }
}

export function orderPriorityToJSON(object: OrderPriority): string {
  switch (object) {
    case OrderPriority.ORDER_PRIORITY_UNSPECIFIED:
      return "ORDER_PRIORITY_UNSPECIFIED";
    case OrderPriority.ORDER_PRIORITY_STANDARD:
      return "ORDER_PRIORITY_STANDARD";
    case OrderPriority.ORDER_PRIORITY_HIGH:
      return "ORDER_PRIORITY_HIGH";
    case OrderPriority.ORDER_PRIORITY_CRITICAL:
      return "ORDER_PRIORITY_CRITICAL";
    case OrderPriority.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ProductType {
  PRODUCT_TYPE_UNSPECIFIED = 0,
  PRODUCT_TYPE_MEDICINE = 1,
  PRODUCT_TYPE_VACCINE = 2,
  PRODUCT_TYPE_BLOOD = 3,
  PRODUCT_TYPE_ORGAN = 4,
  PRODUCT_TYPE_MEDICAL_DEVICE = 5,
  UNRECOGNIZED = -1,
}

export function productTypeFromJSON(object: any): ProductType {
  switch (object) {
    case 0:
    case "PRODUCT_TYPE_UNSPECIFIED":
      return ProductType.PRODUCT_TYPE_UNSPECIFIED;
    case 1:
    case "PRODUCT_TYPE_MEDICINE":
      return ProductType.PRODUCT_TYPE_MEDICINE;
    case 2:
    case "PRODUCT_TYPE_VACCINE":
      return ProductType.PRODUCT_TYPE_VACCINE;
    case 3:
    case "PRODUCT_TYPE_BLOOD":
      return ProductType.PRODUCT_TYPE_BLOOD;
    case 4:
    case "PRODUCT_TYPE_ORGAN":
      return ProductType.PRODUCT_TYPE_ORGAN;
    case 5:
    case "PRODUCT_TYPE_MEDICAL_DEVICE":
      return ProductType.PRODUCT_TYPE_MEDICAL_DEVICE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProductType.UNRECOGNIZED;
  }
}

export function productTypeToJSON(object: ProductType): string {
  switch (object) {
    case ProductType.PRODUCT_TYPE_UNSPECIFIED:
      return "PRODUCT_TYPE_UNSPECIFIED";
    case ProductType.PRODUCT_TYPE_MEDICINE:
      return "PRODUCT_TYPE_MEDICINE";
    case ProductType.PRODUCT_TYPE_VACCINE:
      return "PRODUCT_TYPE_VACCINE";
    case ProductType.PRODUCT_TYPE_BLOOD:
      return "PRODUCT_TYPE_BLOOD";
    case ProductType.PRODUCT_TYPE_ORGAN:
      return "PRODUCT_TYPE_ORGAN";
    case ProductType.PRODUCT_TYPE_MEDICAL_DEVICE:
      return "PRODUCT_TYPE_MEDICAL_DEVICE";
    case ProductType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ActionType {
  ACTION_TYPE_UNSPECIFIED = 0,
  ACTION_TYPE_FLY_TO = 1,
  ACTION_TYPE_PICKUP = 2,
  ACTION_TYPE_DROPOFF = 3,
  ACTION_TYPE_CHARGE = 4,
  UNRECOGNIZED = -1,
}

export function actionTypeFromJSON(object: any): ActionType {
  switch (object) {
    case 0:
    case "ACTION_TYPE_UNSPECIFIED":
      return ActionType.ACTION_TYPE_UNSPECIFIED;
    case 1:
    case "ACTION_TYPE_FLY_TO":
      return ActionType.ACTION_TYPE_FLY_TO;
    case 2:
    case "ACTION_TYPE_PICKUP":
      return ActionType.ACTION_TYPE_PICKUP;
    case 3:
    case "ACTION_TYPE_DROPOFF":
      return ActionType.ACTION_TYPE_DROPOFF;
    case 4:
    case "ACTION_TYPE_CHARGE":
      return ActionType.ACTION_TYPE_CHARGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActionType.UNRECOGNIZED;
  }
}

export function actionTypeToJSON(object: ActionType): string {
  switch (object) {
    case ActionType.ACTION_TYPE_UNSPECIFIED:
      return "ACTION_TYPE_UNSPECIFIED";
    case ActionType.ACTION_TYPE_FLY_TO:
      return "ACTION_TYPE_FLY_TO";
    case ActionType.ACTION_TYPE_PICKUP:
      return "ACTION_TYPE_PICKUP";
    case ActionType.ACTION_TYPE_DROPOFF:
      return "ACTION_TYPE_DROPOFF";
    case ActionType.ACTION_TYPE_CHARGE:
      return "ACTION_TYPE_CHARGE";
    case ActionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WaypointType {
  WAYPOINT_TYPE_UNSPECIFIED = 0,
  WAYPOINT_TYPE_DEPOT_START = 1,
  WAYPOINT_TYPE_WAREHOUSE_PICKUP = 2,
  WAYPOINT_TYPE_HOSPITAL_DELIVERY = 3,
  WAYPOINT_TYPE_DEPOT_RETURN = 4,
  UNRECOGNIZED = -1,
}

export function waypointTypeFromJSON(object: any): WaypointType {
  switch (object) {
    case 0:
    case "WAYPOINT_TYPE_UNSPECIFIED":
      return WaypointType.WAYPOINT_TYPE_UNSPECIFIED;
    case 1:
    case "WAYPOINT_TYPE_DEPOT_START":
      return WaypointType.WAYPOINT_TYPE_DEPOT_START;
    case 2:
    case "WAYPOINT_TYPE_WAREHOUSE_PICKUP":
      return WaypointType.WAYPOINT_TYPE_WAREHOUSE_PICKUP;
    case 3:
    case "WAYPOINT_TYPE_HOSPITAL_DELIVERY":
      return WaypointType.WAYPOINT_TYPE_HOSPITAL_DELIVERY;
    case 4:
    case "WAYPOINT_TYPE_DEPOT_RETURN":
      return WaypointType.WAYPOINT_TYPE_DEPOT_RETURN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WaypointType.UNRECOGNIZED;
  }
}

export function waypointTypeToJSON(object: WaypointType): string {
  switch (object) {
    case WaypointType.WAYPOINT_TYPE_UNSPECIFIED:
      return "WAYPOINT_TYPE_UNSPECIFIED";
    case WaypointType.WAYPOINT_TYPE_DEPOT_START:
      return "WAYPOINT_TYPE_DEPOT_START";
    case WaypointType.WAYPOINT_TYPE_WAREHOUSE_PICKUP:
      return "WAYPOINT_TYPE_WAREHOUSE_PICKUP";
    case WaypointType.WAYPOINT_TYPE_HOSPITAL_DELIVERY:
      return "WAYPOINT_TYPE_HOSPITAL_DELIVERY";
    case WaypointType.WAYPOINT_TYPE_DEPOT_RETURN:
      return "WAYPOINT_TYPE_DEPOT_RETURN";
    case WaypointType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Position {
  lat: number;
  lon: number;
}

function createBasePosition(): Position {
  return { lat: 0, lon: 0 };
}

export const Position: MessageFns<Position> = {
  fromJSON(object: any): Position {
    return {
      lat: isSet(object.lat) ? globalThis.Number(object.lat) : 0,
      lon: isSet(object.lon) ? globalThis.Number(object.lon) : 0,
    };
  },

  toJSON(message: Position): unknown {
    const obj: any = {};
    if (message.lat !== 0) {
      obj.lat = message.lat;
    }
    if (message.lon !== 0) {
      obj.lon = message.lon;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Position>, I>>(base?: I): Position {
    return Position.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Position>, I>>(object: I): Position {
    const message = createBasePosition();
    message.lat = object.lat ?? 0;
    message.lon = object.lon ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
