// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: dronefleet/v1/warehouse.proto

/* eslint-disable */
import { Position } from "./common";

export const protobufPackage = "dronefleet.v1";

export interface Warehouse {
  id: string;
  name: string;
  position: Position | undefined;
  authorized_product_types: string[];
  is_cold_storage_capable: boolean;
}

function createBaseWarehouse(): Warehouse {
  return { id: "", name: "", position: undefined, authorized_product_types: [], is_cold_storage_capable: false };
}

export const Warehouse: MessageFns<Warehouse> = {
  fromJSON(object: any): Warehouse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      position: isSet(object.position) ? Position.fromJSON(object.position) : undefined,
      authorized_product_types: globalThis.Array.isArray(object?.authorizedProductTypes)
        ? object.authorizedProductTypes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.authorized_product_types)
        ? object.authorized_product_types.map((e: any) => globalThis.String(e))
        : [],
      is_cold_storage_capable: isSet(object.isColdStorageCapable)
        ? globalThis.Boolean(object.isColdStorageCapable)
        : isSet(object.is_cold_storage_capable)
        ? globalThis.Boolean(object.is_cold_storage_capable)
        : false,
    };
  },

  toJSON(message: Warehouse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.position !== undefined) {
      obj.position = Position.toJSON(message.position);
    }
    if (message.authorized_product_types?.length) {
      obj.authorizedProductTypes = message.authorized_product_types;
    }
    if (message.is_cold_storage_capable !== false) {
      obj.isColdStorageCapable = message.is_cold_storage_capable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Warehouse>, I>>(base?: I): Warehouse {
    return Warehouse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Warehouse>, I>>(object: I): Warehouse {
    const message = createBaseWarehouse();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.position = (object.position !== undefined && object.position !== null)
      ? Position.fromPartial(object.position)
      : undefined;
    message.authorized_product_types = object.authorized_product_types?.map((e) => e) || [];
    message.is_cold_storage_capable = object.is_cold_storage_capable ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
