[project]
name = "simulators"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "dronefleet_shared",
  "fastapi[standard]>=0.126.0",
  "uvicorn>=0.38.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
"dronefleet_shared" = { workspace = true }
