// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032dronefleet/v1/common.proto\022\rdronefleet" +
      ".v1\".\n\010Position\022\020\n\003lat\030\001 \001(\001R\003lat\022\020\n\003lon" +
      "\030\002 \001(\001R\003lon*\234\002\n\013DroneStatus\022\034\n\030DRONE_STA" +
      "TUS_UNSPECIFIED\020\000\022\025\n\021DRONE_STATUS_IDLE\020\001" +
      "\022\031\n\025DRONE_STATUS_RESERVED\020\002\022\027\n\023DRONE_STA" +
      "TUS_MOVING\020\003\022\033\n\027DRONE_STATUS_DELIVERING\020" +
      "\004\022\031\n\025DRONE_STATUS_CHARGING\020\005\022\034\n\030DRONE_ST" +
      "ATUS_MAINTENANCE\020\006\022\030\n\024DRONE_STATUS_PROBL" +
      "EM\020\007\022\032\n\026DRONE_STATUS_EMERGENCY\020\010\022\030\n\024DRON" +
      "E_STATUS_UNKNOWN\020\t*\320\001\n\013OrderStatus\022\034\n\030OR" +
      "DER_STATUS_UNSPECIFIED\020\000\022\030\n\024ORDER_STATUS" +
      "_PENDING\020\001\022\030\n\024ORDER_STATUS_SOLVING\020\002\022\031\n\025" +
      "ORDER_STATUS_ASSIGNED\020\003\022\034\n\030ORDER_STATUS_" +
      "IN_DELIVERY\020\004\022\032\n\026ORDER_STATUS_DELIVERED\020" +
      "\005\022\032\n\026ORDER_STATUS_CANCELLED\020\006*\202\001\n\rOrderP" +
      "riority\022\036\n\032ORDER_PRIORITY_UNSPECIFIED\020\000\022" +
      "\033\n\027ORDER_PRIORITY_STANDARD\020\001\022\027\n\023ORDER_PR" +
      "IORITY_HIGH\020\002\022\033\n\027ORDER_PRIORITY_CRITICAL" +
      "\020\003*\261\001\n\013ProductType\022\034\n\030PRODUCT_TYPE_UNSPE" +
      "CIFIED\020\000\022\031\n\025PRODUCT_TYPE_MEDICINE\020\001\022\030\n\024P" +
      "RODUCT_TYPE_VACCINE\020\002\022\026\n\022PRODUCT_TYPE_BL" +
      "OOD\020\003\022\026\n\022PRODUCT_TYPE_ORGAN\020\004\022\037\n\033PRODUCT" +
      "_TYPE_MEDICAL_DEVICE\020\005*\212\001\n\nActionType\022\033\n" +
      "\027ACTION_TYPE_UNSPECIFIED\020\000\022\026\n\022ACTION_TYP" +
      "E_FLY_TO\020\001\022\026\n\022ACTION_TYPE_PICKUP\020\002\022\027\n\023AC" +
      "TION_TYPE_DROPOFF\020\003\022\026\n\022ACTION_TYPE_CHARG" +
      "E\020\004*\265\001\n\014WaypointType\022\035\n\031WAYPOINT_TYPE_UN" +
      "SPECIFIED\020\000\022\035\n\031WAYPOINT_TYPE_DEPOT_START" +
      "\020\001\022\"\n\036WAYPOINT_TYPE_WAREHOUSE_PICKUP\020\002\022#" +
      "\n\037WAYPOINT_TYPE_HOSPITAL_DELIVERY\020\003\022\036\n\032W" +
      "AYPOINT_TYPE_DEPOT_RETURN\020\004B\200\001\n\034com.dron" +
      "efleet.shared.modelsB\013CommonProtoP\001\242\002\003DX" +
      "X\252\002\rDronefleet.V1\312\002\rDronefleet\\V1\342\002\031Dron" +
      "efleet\\V1\\GPBMetadata\352\002\016Dronefleet::V1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dronefleet_v1_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Position_descriptor,
        new java.lang.String[] { "Lat", "Lon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
