// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/depot.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class DepotProto {
  private DepotProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Depot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Depot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031dronefleet/v1/depot.proto\022\rdronefleet." +
      "v1\032\032dronefleet/v1/common.proto\"\243\001\n\005Depot" +
      "\022\016\n\002id\030\001 \001(\tR\002id\022\022\n\004name\030\002 \001(\tR\004name\0223\n\010" +
      "position\030\003 \001(\0132\027.dronefleet.v1.PositionR" +
      "\010position\022\032\n\010capacity\030\004 \001(\005R\010capacity\022%\n" +
      "\016charging_slots\030\005 \001(\005R\rchargingSlotsB\177\n\034" +
      "com.dronefleet.shared.modelsB\nDepotProto" +
      "P\001\242\002\003DXX\252\002\rDronefleet.V1\312\002\rDronefleet\\V1" +
      "\342\002\031Dronefleet\\V1\\GPBMetadata\352\002\016Droneflee" +
      "t::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dronefleet.shared.models.CommonProto.getDescriptor(),
        });
    internal_static_dronefleet_v1_Depot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_Depot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Depot_descriptor,
        new java.lang.String[] { "Id", "Name", "Position", "Capacity", "ChargingSlots", });
    com.dronefleet.shared.models.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
