// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/depot.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public interface DepotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dronefleet.v1.Depot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return The position.
   */
  com.dronefleet.shared.models.Position getPosition();
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   */
  com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>int32 capacity = 4 [json_name = "capacity"];</code>
   * @return The capacity.
   */
  int getCapacity();

  /**
   * <code>int32 charging_slots = 5 [json_name = "chargingSlots"];</code>
   * @return The chargingSlots.
   */
  int getChargingSlots();
}
