// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/drone.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public interface DroneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dronefleet.v1.Drone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  com.dronefleet.shared.models.Position getPosition();
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   */
  com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>double battery_percentage = 3 [json_name = "batteryPercentage"];</code>
   * @return The batteryPercentage.
   */
  double getBatteryPercentage();

  /**
   * <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
   * @return The speedKmh.
   */
  double getSpeedKmh();

  /**
   * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
   * @return The status.
   */
  com.dronefleet.shared.models.DroneStatus getStatus();

  /**
   * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
   * @return The currentMissionId.
   */
  java.lang.String getCurrentMissionId();
  /**
   * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
   * @return The bytes for currentMissionId.
   */
  com.google.protobuf.ByteString
      getCurrentMissionIdBytes();

  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   * @return Whether the lastUpdate field is set.
   */
  boolean hasLastUpdate();
  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   * @return The lastUpdate.
   */
  com.google.protobuf.Timestamp getLastUpdate();
  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdateOrBuilder();

  /**
   * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
   * @return The solvingSessionId.
   */
  java.lang.String getSolvingSessionId();
  /**
   * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
   * @return The bytes for solvingSessionId.
   */
  com.google.protobuf.ByteString
      getSolvingSessionIdBytes();

  /**
   * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
   * @return The homeDepotId.
   */
  java.lang.String getHomeDepotId();
  /**
   * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
   * @return The bytes for homeDepotId.
   */
  com.google.protobuf.ByteString
      getHomeDepotIdBytes();

  /**
   * <code>int32 battery_capacity_mah = 10 [json_name = "batteryCapacityMah"];</code>
   * @return The batteryCapacityMah.
   */
  int getBatteryCapacityMah();

  /**
   * <code>double consumption_per_km = 11 [json_name = "consumptionPerKm"];</code>
   * @return The consumptionPerKm.
   */
  double getConsumptionPerKm();

  /**
   * <code>int32 max_flight_time_minutes = 12 [json_name = "maxFlightTimeMinutes"];</code>
   * @return The maxFlightTimeMinutes.
   */
  int getMaxFlightTimeMinutes();
}
