// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/drone.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.DroneTelemetry}
 */
public final class DroneTelemetry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.DroneTelemetry)
    DroneTelemetryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DroneTelemetry.newBuilder() to construct.
  private DroneTelemetry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DroneTelemetry() {
    droneId_ = "";
    status_ = 0;
    currentMissionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DroneTelemetry();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_DroneTelemetry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_DroneTelemetry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.DroneTelemetry.class, com.dronefleet.shared.models.DroneTelemetry.Builder.class);
  }

  private int bitField0_;
  public static final int DRONE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object droneId_ = "";
  /**
   * <code>string drone_id = 1 [json_name = "droneId"];</code>
   * @return The droneId.
   */
  @java.lang.Override
  public java.lang.String getDroneId() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      droneId_ = s;
      return s;
    }
  }
  /**
   * <code>string drone_id = 1 [json_name = "droneId"];</code>
   * @return The bytes for droneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDroneIdBytes() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      droneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private com.dronefleet.shared.models.Position position_;
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return The position.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Position getPosition() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }

  public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 4;
  private double batteryPercentage_ = 0D;
  /**
   * <code>double battery_percentage = 4 [json_name = "batteryPercentage"];</code>
   * @return The batteryPercentage.
   */
  @java.lang.Override
  public double getBatteryPercentage() {
    return batteryPercentage_;
  }

  public static final int SPEED_KMH_FIELD_NUMBER = 5;
  private double speedKmh_ = 0D;
  /**
   * <code>double speed_kmh = 5 [json_name = "speedKmh"];</code>
   * @return The speedKmh.
   */
  @java.lang.Override
  public double getSpeedKmh() {
    return speedKmh_;
  }

  public static final int STATUS_FIELD_NUMBER = 6;
  private int status_ = 0;
  /**
   * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.dronefleet.shared.models.DroneStatus getStatus() {
    com.dronefleet.shared.models.DroneStatus result = com.dronefleet.shared.models.DroneStatus.forNumber(status_);
    return result == null ? com.dronefleet.shared.models.DroneStatus.UNRECOGNIZED : result;
  }

  public static final int CURRENT_MISSION_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currentMissionId_ = "";
  /**
   * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
   * @return The currentMissionId.
   */
  @java.lang.Override
  public java.lang.String getCurrentMissionId() {
    java.lang.Object ref = currentMissionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentMissionId_ = s;
      return s;
    }
  }
  /**
   * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
   * @return The bytes for currentMissionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentMissionIdBytes() {
    java.lang.Object ref = currentMissionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentMissionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(droneId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, droneId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPosition());
    }
    if (java.lang.Double.doubleToRawLongBits(batteryPercentage_) != 0) {
      output.writeDouble(4, batteryPercentage_);
    }
    if (java.lang.Double.doubleToRawLongBits(speedKmh_) != 0) {
      output.writeDouble(5, speedKmh_);
    }
    if (status_ != com.dronefleet.shared.models.DroneStatus.DRONE_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(6, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentMissionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, currentMissionId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(droneId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, droneId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPosition());
    }
    if (java.lang.Double.doubleToRawLongBits(batteryPercentage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, batteryPercentage_);
    }
    if (java.lang.Double.doubleToRawLongBits(speedKmh_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, speedKmh_);
    }
    if (status_ != com.dronefleet.shared.models.DroneStatus.DRONE_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentMissionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, currentMissionId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.DroneTelemetry)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.DroneTelemetry other = (com.dronefleet.shared.models.DroneTelemetry) obj;

    if (!getDroneId()
        .equals(other.getDroneId())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getBatteryPercentage())
        != java.lang.Double.doubleToLongBits(
            other.getBatteryPercentage())) return false;
    if (java.lang.Double.doubleToLongBits(getSpeedKmh())
        != java.lang.Double.doubleToLongBits(
            other.getSpeedKmh())) return false;
    if (status_ != other.status_) return false;
    if (!getCurrentMissionId()
        .equals(other.getCurrentMissionId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DRONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDroneId().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBatteryPercentage()));
    hash = (37 * hash) + SPEED_KMH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSpeedKmh()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CURRENT_MISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentMissionId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.DroneTelemetry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.DroneTelemetry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.DroneTelemetry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.DroneTelemetry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.DroneTelemetry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.DroneTelemetry)
      com.dronefleet.shared.models.DroneTelemetryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_DroneTelemetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_DroneTelemetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.DroneTelemetry.class, com.dronefleet.shared.models.DroneTelemetry.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.DroneTelemetry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTimestampFieldBuilder();
        getPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      droneId_ = "";
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      batteryPercentage_ = 0D;
      speedKmh_ = 0D;
      status_ = 0;
      currentMissionId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_DroneTelemetry_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.DroneTelemetry getDefaultInstanceForType() {
      return com.dronefleet.shared.models.DroneTelemetry.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.DroneTelemetry build() {
      com.dronefleet.shared.models.DroneTelemetry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.DroneTelemetry buildPartial() {
      com.dronefleet.shared.models.DroneTelemetry result = new com.dronefleet.shared.models.DroneTelemetry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dronefleet.shared.models.DroneTelemetry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.droneId_ = droneId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.batteryPercentage_ = batteryPercentage_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.speedKmh_ = speedKmh_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.currentMissionId_ = currentMissionId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.DroneTelemetry) {
        return mergeFrom((com.dronefleet.shared.models.DroneTelemetry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.DroneTelemetry other) {
      if (other == com.dronefleet.shared.models.DroneTelemetry.getDefaultInstance()) return this;
      if (!other.getDroneId().isEmpty()) {
        droneId_ = other.droneId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.getBatteryPercentage() != 0D) {
        setBatteryPercentage(other.getBatteryPercentage());
      }
      if (other.getSpeedKmh() != 0D) {
        setSpeedKmh(other.getSpeedKmh());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getCurrentMissionId().isEmpty()) {
        currentMissionId_ = other.currentMissionId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              droneId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 33: {
              batteryPercentage_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              speedKmh_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              currentMissionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object droneId_ = "";
    /**
     * <code>string drone_id = 1 [json_name = "droneId"];</code>
     * @return The droneId.
     */
    public java.lang.String getDroneId() {
      java.lang.Object ref = droneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        droneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drone_id = 1 [json_name = "droneId"];</code>
     * @return The bytes for droneId.
     */
    public com.google.protobuf.ByteString
        getDroneIdBytes() {
      java.lang.Object ref = droneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        droneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drone_id = 1 [json_name = "droneId"];</code>
     * @param value The droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      droneId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 1 [json_name = "droneId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDroneId() {
      droneId_ = getDefaultInstance().getDroneId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 1 [json_name = "droneId"];</code>
     * @param value The bytes for droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      droneId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.dronefleet.shared.models.Position position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> positionBuilder_;
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     * @return The position.
     */
    public com.dronefleet.shared.models.Position getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public Builder setPosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public Builder setPosition(
        com.dronefleet.shared.models.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public Builder mergePosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          position_ != null &&
          position_ != com.dronefleet.shared.models.Position.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000004);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.Position.Builder getPositionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private double batteryPercentage_ ;
    /**
     * <code>double battery_percentage = 4 [json_name = "batteryPercentage"];</code>
     * @return The batteryPercentage.
     */
    @java.lang.Override
    public double getBatteryPercentage() {
      return batteryPercentage_;
    }
    /**
     * <code>double battery_percentage = 4 [json_name = "batteryPercentage"];</code>
     * @param value The batteryPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryPercentage(double value) {

      batteryPercentage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double battery_percentage = 4 [json_name = "batteryPercentage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryPercentage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      batteryPercentage_ = 0D;
      onChanged();
      return this;
    }

    private double speedKmh_ ;
    /**
     * <code>double speed_kmh = 5 [json_name = "speedKmh"];</code>
     * @return The speedKmh.
     */
    @java.lang.Override
    public double getSpeedKmh() {
      return speedKmh_;
    }
    /**
     * <code>double speed_kmh = 5 [json_name = "speedKmh"];</code>
     * @param value The speedKmh to set.
     * @return This builder for chaining.
     */
    public Builder setSpeedKmh(double value) {

      speedKmh_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double speed_kmh = 5 [json_name = "speedKmh"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeedKmh() {
      bitField0_ = (bitField0_ & ~0x00000010);
      speedKmh_ = 0D;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.dronefleet.shared.models.DroneStatus getStatus() {
      com.dronefleet.shared.models.DroneStatus result = com.dronefleet.shared.models.DroneStatus.forNumber(status_);
      return result == null ? com.dronefleet.shared.models.DroneStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.dronefleet.shared.models.DroneStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 6 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000020);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currentMissionId_ = "";
    /**
     * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
     * @return The currentMissionId.
     */
    public java.lang.String getCurrentMissionId() {
      java.lang.Object ref = currentMissionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentMissionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
     * @return The bytes for currentMissionId.
     */
    public com.google.protobuf.ByteString
        getCurrentMissionIdBytes() {
      java.lang.Object ref = currentMissionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentMissionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
     * @param value The currentMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentMissionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currentMissionId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentMissionId() {
      currentMissionId_ = getDefaultInstance().getCurrentMissionId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string current_mission_id = 7 [json_name = "currentMissionId"];</code>
     * @param value The bytes for currentMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentMissionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currentMissionId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.DroneTelemetry)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.DroneTelemetry)
  private static final com.dronefleet.shared.models.DroneTelemetry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.DroneTelemetry();
  }

  public static com.dronefleet.shared.models.DroneTelemetry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DroneTelemetry>
      PARSER = new com.google.protobuf.AbstractParser<DroneTelemetry>() {
    @java.lang.Override
    public DroneTelemetry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DroneTelemetry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DroneTelemetry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.DroneTelemetry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

