// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/drone.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class DroneProto {
  private DroneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Drone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Drone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_DroneTelemetry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_DroneTelemetry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031dronefleet/v1/drone.proto\022\rdronefleet." +
      "v1\032\032dronefleet/v1/common.proto\032\037google/p" +
      "rotobuf/timestamp.proto\"\240\004\n\005Drone\022\016\n\002id\030" +
      "\001 \001(\tR\002id\0223\n\010position\030\002 \001(\0132\027.dronefleet" +
      ".v1.PositionR\010position\022-\n\022battery_percen" +
      "tage\030\003 \001(\001R\021batteryPercentage\022\033\n\tspeed_k" +
      "mh\030\004 \001(\001R\010speedKmh\0222\n\006status\030\005 \001(\0162\032.dro" +
      "nefleet.v1.DroneStatusR\006status\022,\n\022curren" +
      "t_mission_id\030\006 \001(\tR\020currentMissionId\022;\n\013" +
      "last_update\030\007 \001(\0132\032.google.protobuf.Time" +
      "stampR\nlastUpdate\022,\n\022solving_session_id\030" +
      "\010 \001(\tR\020solvingSessionId\022\"\n\rhome_depot_id" +
      "\030\t \001(\tR\013homeDepotId\0220\n\024battery_capacity_" +
      "mah\030\n \001(\005R\022batteryCapacityMah\022,\n\022consump" +
      "tion_per_km\030\013 \001(\001R\020consumptionPerKm\0225\n\027m" +
      "ax_flight_time_minutes\030\014 \001(\005R\024maxFlightT" +
      "imeMinutes\"\310\002\n\016DroneTelemetry\022\031\n\010drone_i" +
      "d\030\001 \001(\tR\007droneId\0228\n\ttimestamp\030\002 \001(\0132\032.go" +
      "ogle.protobuf.TimestampR\ttimestamp\0223\n\010po" +
      "sition\030\003 \001(\0132\027.dronefleet.v1.PositionR\010p" +
      "osition\022-\n\022battery_percentage\030\004 \001(\001R\021bat" +
      "teryPercentage\022\033\n\tspeed_kmh\030\005 \001(\001R\010speed" +
      "Kmh\0222\n\006status\030\006 \001(\0162\032.dronefleet.v1.Dron" +
      "eStatusR\006status\022,\n\022current_mission_id\030\007 " +
      "\001(\tR\020currentMissionIdB\177\n\034com.dronefleet." +
      "shared.modelsB\nDroneProtoP\001\242\002\003DXX\252\002\rDron" +
      "efleet.V1\312\002\rDronefleet\\V1\342\002\031Dronefleet\\V" +
      "1\\GPBMetadata\352\002\016Dronefleet::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dronefleet.shared.models.CommonProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_dronefleet_v1_Drone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_Drone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Drone_descriptor,
        new java.lang.String[] { "Id", "Position", "BatteryPercentage", "SpeedKmh", "Status", "CurrentMissionId", "LastUpdate", "SolvingSessionId", "HomeDepotId", "BatteryCapacityMah", "ConsumptionPerKm", "MaxFlightTimeMinutes", });
    internal_static_dronefleet_v1_DroneTelemetry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dronefleet_v1_DroneTelemetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_DroneTelemetry_descriptor,
        new java.lang.String[] { "DroneId", "Timestamp", "Position", "BatteryPercentage", "SpeedKmh", "Status", "CurrentMissionId", });
    com.dronefleet.shared.models.CommonProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
