// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf enum {@code dronefleet.v1.DroneStatus}
 */
public enum DroneStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DRONE_STATUS_UNSPECIFIED = 0;</code>
   */
  DRONE_STATUS_UNSPECIFIED(0),
  /**
   * <code>DRONE_STATUS_IDLE = 1;</code>
   */
  DRONE_STATUS_IDLE(1),
  /**
   * <code>DRONE_STATUS_RESERVED = 2;</code>
   */
  DRONE_STATUS_RESERVED(2),
  /**
   * <code>DRONE_STATUS_MOVING = 3;</code>
   */
  DRONE_STATUS_MOVING(3),
  /**
   * <code>DRONE_STATUS_DELIVERING = 4;</code>
   */
  DRONE_STATUS_DELIVERING(4),
  /**
   * <code>DRONE_STATUS_CHARGING = 5;</code>
   */
  DRONE_STATUS_CHARGING(5),
  /**
   * <code>DRONE_STATUS_MAINTENANCE = 6;</code>
   */
  DRONE_STATUS_MAINTENANCE(6),
  /**
   * <code>DRONE_STATUS_PROBLEM = 7;</code>
   */
  DRONE_STATUS_PROBLEM(7),
  /**
   * <code>DRONE_STATUS_EMERGENCY = 8;</code>
   */
  DRONE_STATUS_EMERGENCY(8),
  /**
   * <code>DRONE_STATUS_UNKNOWN = 9;</code>
   */
  DRONE_STATUS_UNKNOWN(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DRONE_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int DRONE_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DRONE_STATUS_IDLE = 1;</code>
   */
  public static final int DRONE_STATUS_IDLE_VALUE = 1;
  /**
   * <code>DRONE_STATUS_RESERVED = 2;</code>
   */
  public static final int DRONE_STATUS_RESERVED_VALUE = 2;
  /**
   * <code>DRONE_STATUS_MOVING = 3;</code>
   */
  public static final int DRONE_STATUS_MOVING_VALUE = 3;
  /**
   * <code>DRONE_STATUS_DELIVERING = 4;</code>
   */
  public static final int DRONE_STATUS_DELIVERING_VALUE = 4;
  /**
   * <code>DRONE_STATUS_CHARGING = 5;</code>
   */
  public static final int DRONE_STATUS_CHARGING_VALUE = 5;
  /**
   * <code>DRONE_STATUS_MAINTENANCE = 6;</code>
   */
  public static final int DRONE_STATUS_MAINTENANCE_VALUE = 6;
  /**
   * <code>DRONE_STATUS_PROBLEM = 7;</code>
   */
  public static final int DRONE_STATUS_PROBLEM_VALUE = 7;
  /**
   * <code>DRONE_STATUS_EMERGENCY = 8;</code>
   */
  public static final int DRONE_STATUS_EMERGENCY_VALUE = 8;
  /**
   * <code>DRONE_STATUS_UNKNOWN = 9;</code>
   */
  public static final int DRONE_STATUS_UNKNOWN_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DroneStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DroneStatus forNumber(int value) {
    switch (value) {
      case 0: return DRONE_STATUS_UNSPECIFIED;
      case 1: return DRONE_STATUS_IDLE;
      case 2: return DRONE_STATUS_RESERVED;
      case 3: return DRONE_STATUS_MOVING;
      case 4: return DRONE_STATUS_DELIVERING;
      case 5: return DRONE_STATUS_CHARGING;
      case 6: return DRONE_STATUS_MAINTENANCE;
      case 7: return DRONE_STATUS_PROBLEM;
      case 8: return DRONE_STATUS_EMERGENCY;
      case 9: return DRONE_STATUS_UNKNOWN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DroneStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DroneStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DroneStatus>() {
          public DroneStatus findValueByNumber(int number) {
            return DroneStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dronefleet.shared.models.CommonProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final DroneStatus[] VALUES = values();

  public static DroneStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DroneStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dronefleet.v1.DroneStatus)
}

