// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/drone.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.Drone}
 */
public final class Drone extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.Drone)
    DroneOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Drone.newBuilder() to construct.
  private Drone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Drone() {
    id_ = "";
    status_ = 0;
    currentMissionId_ = "";
    solvingSessionId_ = "";
    homeDepotId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Drone();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_Drone_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_Drone_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.Drone.class, com.dronefleet.shared.models.Drone.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.dronefleet.shared.models.Position position_;
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Position getPosition() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }

  public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 3;
  private double batteryPercentage_ = 0D;
  /**
   * <code>double battery_percentage = 3 [json_name = "batteryPercentage"];</code>
   * @return The batteryPercentage.
   */
  @java.lang.Override
  public double getBatteryPercentage() {
    return batteryPercentage_;
  }

  public static final int SPEED_KMH_FIELD_NUMBER = 4;
  private double speedKmh_ = 0D;
  /**
   * <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
   * @return The speedKmh.
   */
  @java.lang.Override
  public double getSpeedKmh() {
    return speedKmh_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_ = 0;
  /**
   * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.dronefleet.shared.models.DroneStatus getStatus() {
    com.dronefleet.shared.models.DroneStatus result = com.dronefleet.shared.models.DroneStatus.forNumber(status_);
    return result == null ? com.dronefleet.shared.models.DroneStatus.UNRECOGNIZED : result;
  }

  public static final int CURRENT_MISSION_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currentMissionId_ = "";
  /**
   * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
   * @return The currentMissionId.
   */
  @java.lang.Override
  public java.lang.String getCurrentMissionId() {
    java.lang.Object ref = currentMissionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentMissionId_ = s;
      return s;
    }
  }
  /**
   * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
   * @return The bytes for currentMissionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentMissionIdBytes() {
    java.lang.Object ref = currentMissionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentMissionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_UPDATE_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp lastUpdate_;
  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   * @return Whether the lastUpdate field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   * @return The lastUpdate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdate() {
    return lastUpdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdate_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdateOrBuilder() {
    return lastUpdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdate_;
  }

  public static final int SOLVING_SESSION_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object solvingSessionId_ = "";
  /**
   * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
   * @return The solvingSessionId.
   */
  @java.lang.Override
  public java.lang.String getSolvingSessionId() {
    java.lang.Object ref = solvingSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      solvingSessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
   * @return The bytes for solvingSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSolvingSessionIdBytes() {
    java.lang.Object ref = solvingSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      solvingSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOME_DEPOT_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object homeDepotId_ = "";
  /**
   * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
   * @return The homeDepotId.
   */
  @java.lang.Override
  public java.lang.String getHomeDepotId() {
    java.lang.Object ref = homeDepotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      homeDepotId_ = s;
      return s;
    }
  }
  /**
   * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
   * @return The bytes for homeDepotId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHomeDepotIdBytes() {
    java.lang.Object ref = homeDepotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      homeDepotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATTERY_CAPACITY_MAH_FIELD_NUMBER = 10;
  private int batteryCapacityMah_ = 0;
  /**
   * <code>int32 battery_capacity_mah = 10 [json_name = "batteryCapacityMah"];</code>
   * @return The batteryCapacityMah.
   */
  @java.lang.Override
  public int getBatteryCapacityMah() {
    return batteryCapacityMah_;
  }

  public static final int CONSUMPTION_PER_KM_FIELD_NUMBER = 11;
  private double consumptionPerKm_ = 0D;
  /**
   * <code>double consumption_per_km = 11 [json_name = "consumptionPerKm"];</code>
   * @return The consumptionPerKm.
   */
  @java.lang.Override
  public double getConsumptionPerKm() {
    return consumptionPerKm_;
  }

  public static final int MAX_FLIGHT_TIME_MINUTES_FIELD_NUMBER = 12;
  private int maxFlightTimeMinutes_ = 0;
  /**
   * <code>int32 max_flight_time_minutes = 12 [json_name = "maxFlightTimeMinutes"];</code>
   * @return The maxFlightTimeMinutes.
   */
  @java.lang.Override
  public int getMaxFlightTimeMinutes() {
    return maxFlightTimeMinutes_;
  }

  public static final int YEAR_OF_USAGES_FIELD_NUMBER = 14;
  private int yearOfUsages_ = 0;
  /**
   * <code>int32 year_of_usages = 14 [json_name = "yearOfUsages"];</code>
   * @return The yearOfUsages.
   */
  @java.lang.Override
  public int getYearOfUsages() {
    return yearOfUsages_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPosition());
    }
    if (java.lang.Double.doubleToRawLongBits(batteryPercentage_) != 0) {
      output.writeDouble(3, batteryPercentage_);
    }
    if (java.lang.Double.doubleToRawLongBits(speedKmh_) != 0) {
      output.writeDouble(4, speedKmh_);
    }
    if (status_ != com.dronefleet.shared.models.DroneStatus.DRONE_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentMissionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, currentMissionId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getLastUpdate());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(solvingSessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, solvingSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeDepotId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, homeDepotId_);
    }
    if (batteryCapacityMah_ != 0) {
      output.writeInt32(10, batteryCapacityMah_);
    }
    if (java.lang.Double.doubleToRawLongBits(consumptionPerKm_) != 0) {
      output.writeDouble(11, consumptionPerKm_);
    }
    if (maxFlightTimeMinutes_ != 0) {
      output.writeInt32(12, maxFlightTimeMinutes_);
    }
    if (yearOfUsages_ != 0) {
      output.writeInt32(14, yearOfUsages_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (java.lang.Double.doubleToRawLongBits(batteryPercentage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, batteryPercentage_);
    }
    if (java.lang.Double.doubleToRawLongBits(speedKmh_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, speedKmh_);
    }
    if (status_ != com.dronefleet.shared.models.DroneStatus.DRONE_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentMissionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, currentMissionId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLastUpdate());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(solvingSessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, solvingSessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeDepotId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, homeDepotId_);
    }
    if (batteryCapacityMah_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, batteryCapacityMah_);
    }
    if (java.lang.Double.doubleToRawLongBits(consumptionPerKm_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, consumptionPerKm_);
    }
    if (maxFlightTimeMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, maxFlightTimeMinutes_);
    }
    if (yearOfUsages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, yearOfUsages_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.Drone)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.Drone other = (com.dronefleet.shared.models.Drone) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getBatteryPercentage())
        != java.lang.Double.doubleToLongBits(
            other.getBatteryPercentage())) return false;
    if (java.lang.Double.doubleToLongBits(getSpeedKmh())
        != java.lang.Double.doubleToLongBits(
            other.getSpeedKmh())) return false;
    if (status_ != other.status_) return false;
    if (!getCurrentMissionId()
        .equals(other.getCurrentMissionId())) return false;
    if (hasLastUpdate() != other.hasLastUpdate()) return false;
    if (hasLastUpdate()) {
      if (!getLastUpdate()
          .equals(other.getLastUpdate())) return false;
    }
    if (!getSolvingSessionId()
        .equals(other.getSolvingSessionId())) return false;
    if (!getHomeDepotId()
        .equals(other.getHomeDepotId())) return false;
    if (getBatteryCapacityMah()
        != other.getBatteryCapacityMah()) return false;
    if (java.lang.Double.doubleToLongBits(getConsumptionPerKm())
        != java.lang.Double.doubleToLongBits(
            other.getConsumptionPerKm())) return false;
    if (getMaxFlightTimeMinutes()
        != other.getMaxFlightTimeMinutes()) return false;
    if (getYearOfUsages()
        != other.getYearOfUsages()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBatteryPercentage()));
    hash = (37 * hash) + SPEED_KMH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSpeedKmh()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CURRENT_MISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentMissionId().hashCode();
    if (hasLastUpdate()) {
      hash = (37 * hash) + LAST_UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdate().hashCode();
    }
    hash = (37 * hash) + SOLVING_SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSolvingSessionId().hashCode();
    hash = (37 * hash) + HOME_DEPOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getHomeDepotId().hashCode();
    hash = (37 * hash) + BATTERY_CAPACITY_MAH_FIELD_NUMBER;
    hash = (53 * hash) + getBatteryCapacityMah();
    hash = (37 * hash) + CONSUMPTION_PER_KM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getConsumptionPerKm()));
    hash = (37 * hash) + MAX_FLIGHT_TIME_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxFlightTimeMinutes();
    hash = (37 * hash) + YEAR_OF_USAGES_FIELD_NUMBER;
    hash = (53 * hash) + getYearOfUsages();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.Drone parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.Drone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.Drone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Drone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.Drone prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.Drone}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.Drone)
      com.dronefleet.shared.models.DroneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_Drone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_Drone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.Drone.class, com.dronefleet.shared.models.Drone.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.Drone.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
        getLastUpdateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      batteryPercentage_ = 0D;
      speedKmh_ = 0D;
      status_ = 0;
      currentMissionId_ = "";
      lastUpdate_ = null;
      if (lastUpdateBuilder_ != null) {
        lastUpdateBuilder_.dispose();
        lastUpdateBuilder_ = null;
      }
      solvingSessionId_ = "";
      homeDepotId_ = "";
      batteryCapacityMah_ = 0;
      consumptionPerKm_ = 0D;
      maxFlightTimeMinutes_ = 0;
      yearOfUsages_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.DroneProto.internal_static_dronefleet_v1_Drone_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Drone getDefaultInstanceForType() {
      return com.dronefleet.shared.models.Drone.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Drone build() {
      com.dronefleet.shared.models.Drone result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Drone buildPartial() {
      com.dronefleet.shared.models.Drone result = new com.dronefleet.shared.models.Drone(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dronefleet.shared.models.Drone result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.batteryPercentage_ = batteryPercentage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.speedKmh_ = speedKmh_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.currentMissionId_ = currentMissionId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lastUpdate_ = lastUpdateBuilder_ == null
            ? lastUpdate_
            : lastUpdateBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.solvingSessionId_ = solvingSessionId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.homeDepotId_ = homeDepotId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.batteryCapacityMah_ = batteryCapacityMah_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.consumptionPerKm_ = consumptionPerKm_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.maxFlightTimeMinutes_ = maxFlightTimeMinutes_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.yearOfUsages_ = yearOfUsages_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.Drone) {
        return mergeFrom((com.dronefleet.shared.models.Drone)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.Drone other) {
      if (other == com.dronefleet.shared.models.Drone.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.getBatteryPercentage() != 0D) {
        setBatteryPercentage(other.getBatteryPercentage());
      }
      if (other.getSpeedKmh() != 0D) {
        setSpeedKmh(other.getSpeedKmh());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getCurrentMissionId().isEmpty()) {
        currentMissionId_ = other.currentMissionId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasLastUpdate()) {
        mergeLastUpdate(other.getLastUpdate());
      }
      if (!other.getSolvingSessionId().isEmpty()) {
        solvingSessionId_ = other.solvingSessionId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getHomeDepotId().isEmpty()) {
        homeDepotId_ = other.homeDepotId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getBatteryCapacityMah() != 0) {
        setBatteryCapacityMah(other.getBatteryCapacityMah());
      }
      if (other.getConsumptionPerKm() != 0D) {
        setConsumptionPerKm(other.getConsumptionPerKm());
      }
      if (other.getMaxFlightTimeMinutes() != 0) {
        setMaxFlightTimeMinutes(other.getMaxFlightTimeMinutes());
      }
      if (other.getYearOfUsages() != 0) {
        setYearOfUsages(other.getYearOfUsages());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              batteryPercentage_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              speedKmh_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              currentMissionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getLastUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              solvingSessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              homeDepotId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              batteryCapacityMah_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 89: {
              consumptionPerKm_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 96: {
              maxFlightTimeMinutes_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 112: {
              yearOfUsages_ = input.readInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 112
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.dronefleet.shared.models.Position position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> positionBuilder_;
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     * @return The position.
     */
    public com.dronefleet.shared.models.Position getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(
        com.dronefleet.shared.models.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder mergePosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          position_ != null &&
          position_ != com.dronefleet.shared.models.Position.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.Position.Builder getPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private double batteryPercentage_ ;
    /**
     * <code>double battery_percentage = 3 [json_name = "batteryPercentage"];</code>
     * @return The batteryPercentage.
     */
    @java.lang.Override
    public double getBatteryPercentage() {
      return batteryPercentage_;
    }
    /**
     * <code>double battery_percentage = 3 [json_name = "batteryPercentage"];</code>
     * @param value The batteryPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryPercentage(double value) {

      batteryPercentage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double battery_percentage = 3 [json_name = "batteryPercentage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryPercentage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      batteryPercentage_ = 0D;
      onChanged();
      return this;
    }

    private double speedKmh_ ;
    /**
     * <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     * @return The speedKmh.
     */
    @java.lang.Override
    public double getSpeedKmh() {
      return speedKmh_;
    }
    /**
     * <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     * @param value The speedKmh to set.
     * @return This builder for chaining.
     */
    public Builder setSpeedKmh(double value) {

      speedKmh_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double speed_kmh = 4 [json_name = "speedKmh"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeedKmh() {
      bitField0_ = (bitField0_ & ~0x00000008);
      speedKmh_ = 0D;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.dronefleet.shared.models.DroneStatus getStatus() {
      com.dronefleet.shared.models.DroneStatus result = com.dronefleet.shared.models.DroneStatus.forNumber(status_);
      return result == null ? com.dronefleet.shared.models.DroneStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.dronefleet.shared.models.DroneStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.DroneStatus status = 5 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object currentMissionId_ = "";
    /**
     * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
     * @return The currentMissionId.
     */
    public java.lang.String getCurrentMissionId() {
      java.lang.Object ref = currentMissionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentMissionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
     * @return The bytes for currentMissionId.
     */
    public com.google.protobuf.ByteString
        getCurrentMissionIdBytes() {
      java.lang.Object ref = currentMissionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentMissionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
     * @param value The currentMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentMissionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currentMissionId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentMissionId() {
      currentMissionId_ = getDefaultInstance().getCurrentMissionId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string current_mission_id = 6 [json_name = "currentMissionId"];</code>
     * @param value The bytes for currentMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentMissionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currentMissionId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     * @return Whether the lastUpdate field is set.
     */
    public boolean hasLastUpdate() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     * @return The lastUpdate.
     */
    public com.google.protobuf.Timestamp getLastUpdate() {
      if (lastUpdateBuilder_ == null) {
        return lastUpdate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdate_;
      } else {
        return lastUpdateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public Builder setLastUpdate(com.google.protobuf.Timestamp value) {
      if (lastUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdate_ = value;
      } else {
        lastUpdateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public Builder setLastUpdate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdateBuilder_ == null) {
        lastUpdate_ = builderForValue.build();
      } else {
        lastUpdateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public Builder mergeLastUpdate(com.google.protobuf.Timestamp value) {
      if (lastUpdateBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          lastUpdate_ != null &&
          lastUpdate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getLastUpdateBuilder().mergeFrom(value);
        } else {
          lastUpdate_ = value;
        }
      } else {
        lastUpdateBuilder_.mergeFrom(value);
      }
      if (lastUpdate_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public Builder clearLastUpdate() {
      bitField0_ = (bitField0_ & ~0x00000040);
      lastUpdate_ = null;
      if (lastUpdateBuilder_ != null) {
        lastUpdateBuilder_.dispose();
        lastUpdateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdateBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getLastUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdateOrBuilder() {
      if (lastUpdateBuilder_ != null) {
        return lastUpdateBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_update = 7 [json_name = "lastUpdate"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdateFieldBuilder() {
      if (lastUpdateBuilder_ == null) {
        lastUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdate(),
                getParentForChildren(),
                isClean());
        lastUpdate_ = null;
      }
      return lastUpdateBuilder_;
    }

    private java.lang.Object solvingSessionId_ = "";
    /**
     * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
     * @return The solvingSessionId.
     */
    public java.lang.String getSolvingSessionId() {
      java.lang.Object ref = solvingSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        solvingSessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
     * @return The bytes for solvingSessionId.
     */
    public com.google.protobuf.ByteString
        getSolvingSessionIdBytes() {
      java.lang.Object ref = solvingSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        solvingSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
     * @param value The solvingSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSolvingSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      solvingSessionId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSolvingSessionId() {
      solvingSessionId_ = getDefaultInstance().getSolvingSessionId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string solving_session_id = 8 [json_name = "solvingSessionId"];</code>
     * @param value The bytes for solvingSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSolvingSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      solvingSessionId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object homeDepotId_ = "";
    /**
     * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
     * @return The homeDepotId.
     */
    public java.lang.String getHomeDepotId() {
      java.lang.Object ref = homeDepotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeDepotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
     * @return The bytes for homeDepotId.
     */
    public com.google.protobuf.ByteString
        getHomeDepotIdBytes() {
      java.lang.Object ref = homeDepotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeDepotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
     * @param value The homeDepotId to set.
     * @return This builder for chaining.
     */
    public Builder setHomeDepotId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      homeDepotId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHomeDepotId() {
      homeDepotId_ = getDefaultInstance().getHomeDepotId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string home_depot_id = 9 [json_name = "homeDepotId"];</code>
     * @param value The bytes for homeDepotId to set.
     * @return This builder for chaining.
     */
    public Builder setHomeDepotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      homeDepotId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private int batteryCapacityMah_ ;
    /**
     * <code>int32 battery_capacity_mah = 10 [json_name = "batteryCapacityMah"];</code>
     * @return The batteryCapacityMah.
     */
    @java.lang.Override
    public int getBatteryCapacityMah() {
      return batteryCapacityMah_;
    }
    /**
     * <code>int32 battery_capacity_mah = 10 [json_name = "batteryCapacityMah"];</code>
     * @param value The batteryCapacityMah to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryCapacityMah(int value) {

      batteryCapacityMah_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 battery_capacity_mah = 10 [json_name = "batteryCapacityMah"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryCapacityMah() {
      bitField0_ = (bitField0_ & ~0x00000200);
      batteryCapacityMah_ = 0;
      onChanged();
      return this;
    }

    private double consumptionPerKm_ ;
    /**
     * <code>double consumption_per_km = 11 [json_name = "consumptionPerKm"];</code>
     * @return The consumptionPerKm.
     */
    @java.lang.Override
    public double getConsumptionPerKm() {
      return consumptionPerKm_;
    }
    /**
     * <code>double consumption_per_km = 11 [json_name = "consumptionPerKm"];</code>
     * @param value The consumptionPerKm to set.
     * @return This builder for chaining.
     */
    public Builder setConsumptionPerKm(double value) {

      consumptionPerKm_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>double consumption_per_km = 11 [json_name = "consumptionPerKm"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumptionPerKm() {
      bitField0_ = (bitField0_ & ~0x00000400);
      consumptionPerKm_ = 0D;
      onChanged();
      return this;
    }

    private int maxFlightTimeMinutes_ ;
    /**
     * <code>int32 max_flight_time_minutes = 12 [json_name = "maxFlightTimeMinutes"];</code>
     * @return The maxFlightTimeMinutes.
     */
    @java.lang.Override
    public int getMaxFlightTimeMinutes() {
      return maxFlightTimeMinutes_;
    }
    /**
     * <code>int32 max_flight_time_minutes = 12 [json_name = "maxFlightTimeMinutes"];</code>
     * @param value The maxFlightTimeMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setMaxFlightTimeMinutes(int value) {

      maxFlightTimeMinutes_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_flight_time_minutes = 12 [json_name = "maxFlightTimeMinutes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxFlightTimeMinutes() {
      bitField0_ = (bitField0_ & ~0x00000800);
      maxFlightTimeMinutes_ = 0;
      onChanged();
      return this;
    }

    private int yearOfUsages_ ;
    /**
     * <code>int32 year_of_usages = 14 [json_name = "yearOfUsages"];</code>
     * @return The yearOfUsages.
     */
    @java.lang.Override
    public int getYearOfUsages() {
      return yearOfUsages_;
    }
    /**
     * <code>int32 year_of_usages = 14 [json_name = "yearOfUsages"];</code>
     * @param value The yearOfUsages to set.
     * @return This builder for chaining.
     */
    public Builder setYearOfUsages(int value) {

      yearOfUsages_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year_of_usages = 14 [json_name = "yearOfUsages"];</code>
     * @return This builder for chaining.
     */
    public Builder clearYearOfUsages() {
      bitField0_ = (bitField0_ & ~0x00001000);
      yearOfUsages_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.Drone)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.Drone)
  private static final com.dronefleet.shared.models.Drone DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.Drone();
  }

  public static com.dronefleet.shared.models.Drone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Drone>
      PARSER = new com.google.protobuf.AbstractParser<Drone>() {
    @java.lang.Override
    public Drone parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Drone> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Drone> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.Drone getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

