// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/mission.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.Mission}
 */
public final class Mission extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.Mission)
    MissionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mission.newBuilder() to construct.
  private Mission(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mission() {
    id_ = "";
    droneId_ = "";
    orderIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    route_ = java.util.Collections.emptyList();
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mission();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Mission_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Mission_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.Mission.class, com.dronefleet.shared.models.Mission.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRONE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object droneId_ = "";
  /**
   * <code>string drone_id = 2 [json_name = "droneId"];</code>
   * @return The droneId.
   */
  @java.lang.Override
  public java.lang.String getDroneId() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      droneId_ = s;
      return s;
    }
  }
  /**
   * <code>string drone_id = 2 [json_name = "droneId"];</code>
   * @return The bytes for droneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDroneIdBytes() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      droneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList orderIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
   * @return A list containing the orderIds.
   */
  public com.google.protobuf.ProtocolStringList
      getOrderIdsList() {
    return orderIds_;
  }
  /**
   * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
   * @return The count of orderIds.
   */
  public int getOrderIdsCount() {
    return orderIds_.size();
  }
  /**
   * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
   * @param index The index of the element to return.
   * @return The orderIds at the given index.
   */
  public java.lang.String getOrderIds(int index) {
    return orderIds_.get(index);
  }
  /**
   * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the orderIds at the given index.
   */
  public com.google.protobuf.ByteString
      getOrderIdsBytes(int index) {
    return orderIds_.getByteString(index);
  }

  public static final int ROUTE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.dronefleet.shared.models.Waypoint> route_;
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dronefleet.shared.models.Waypoint> getRouteList() {
    return route_;
  }
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dronefleet.shared.models.WaypointOrBuilder> 
      getRouteOrBuilderList() {
    return route_;
  }
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
   */
  @java.lang.Override
  public int getRouteCount() {
    return route_.size();
  }
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Waypoint getRoute(int index) {
    return route_.get(index);
  }
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.WaypointOrBuilder getRouteOrBuilder(
      int index) {
    return route_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * ACTIVE, COMPLETED, FAILED
   * </pre>
   *
   * <code>string status = 5 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ACTIVE, COMPLETED, FAILED
   * </pre>
   *
   * <code>string status = 5 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIME_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp startTime_;
  /**
   * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
   * @return Whether the startTime field is set.
   */
  @java.lang.Override
  public boolean hasStartTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
   * @return The startTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStartTime() {
    return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
    return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp endTime_;
  /**
   * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
   * @return Whether the endTime field is set.
   */
  @java.lang.Override
  public boolean hasEndTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
   * @return The endTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEndTime() {
    return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
    return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
  }

  public static final int ESTIMATED_BATTERY_CONSUMPTION_FIELD_NUMBER = 8;
  private double estimatedBatteryConsumption_ = 0D;
  /**
   * <code>double estimated_battery_consumption = 8 [json_name = "estimatedBatteryConsumption"];</code>
   * @return The estimatedBatteryConsumption.
   */
  @java.lang.Override
  public double getEstimatedBatteryConsumption() {
    return estimatedBatteryConsumption_;
  }

  public static final int ESTIMATED_DURATION_MINUTES_FIELD_NUMBER = 9;
  private double estimatedDurationMinutes_ = 0D;
  /**
   * <code>double estimated_duration_minutes = 9 [json_name = "estimatedDurationMinutes"];</code>
   * @return The estimatedDurationMinutes.
   */
  @java.lang.Override
  public double getEstimatedDurationMinutes() {
    return estimatedDurationMinutes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(droneId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, droneId_);
    }
    for (int i = 0; i < orderIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderIds_.getRaw(i));
    }
    for (int i = 0; i < route_.size(); i++) {
      output.writeMessage(4, route_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getStartTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getEndTime());
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedBatteryConsumption_) != 0) {
      output.writeDouble(8, estimatedBatteryConsumption_);
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedDurationMinutes_) != 0) {
      output.writeDouble(9, estimatedDurationMinutes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(droneId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, droneId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < orderIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(orderIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOrderIdsList().size();
    }
    for (int i = 0; i < route_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, route_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getStartTime());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getEndTime());
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedBatteryConsumption_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, estimatedBatteryConsumption_);
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedDurationMinutes_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, estimatedDurationMinutes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.Mission)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.Mission other = (com.dronefleet.shared.models.Mission) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getDroneId()
        .equals(other.getDroneId())) return false;
    if (!getOrderIdsList()
        .equals(other.getOrderIdsList())) return false;
    if (!getRouteList()
        .equals(other.getRouteList())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (hasStartTime() != other.hasStartTime()) return false;
    if (hasStartTime()) {
      if (!getStartTime()
          .equals(other.getStartTime())) return false;
    }
    if (hasEndTime() != other.hasEndTime()) return false;
    if (hasEndTime()) {
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getEstimatedBatteryConsumption())
        != java.lang.Double.doubleToLongBits(
            other.getEstimatedBatteryConsumption())) return false;
    if (java.lang.Double.doubleToLongBits(getEstimatedDurationMinutes())
        != java.lang.Double.doubleToLongBits(
            other.getEstimatedDurationMinutes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DRONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDroneId().hashCode();
    if (getOrderIdsCount() > 0) {
      hash = (37 * hash) + ORDER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderIdsList().hashCode();
    }
    if (getRouteCount() > 0) {
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRouteList().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (hasStartTime()) {
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
    }
    if (hasEndTime()) {
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
    }
    hash = (37 * hash) + ESTIMATED_BATTERY_CONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEstimatedBatteryConsumption()));
    hash = (37 * hash) + ESTIMATED_DURATION_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEstimatedDurationMinutes()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.Mission parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.Mission parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.Mission parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Mission parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.Mission prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.Mission}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.Mission)
      com.dronefleet.shared.models.MissionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Mission_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Mission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.Mission.class, com.dronefleet.shared.models.Mission.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.Mission.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRouteFieldBuilder();
        getStartTimeFieldBuilder();
        getEndTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      droneId_ = "";
      orderIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (routeBuilder_ == null) {
        route_ = java.util.Collections.emptyList();
      } else {
        route_ = null;
        routeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = "";
      startTime_ = null;
      if (startTimeBuilder_ != null) {
        startTimeBuilder_.dispose();
        startTimeBuilder_ = null;
      }
      endTime_ = null;
      if (endTimeBuilder_ != null) {
        endTimeBuilder_.dispose();
        endTimeBuilder_ = null;
      }
      estimatedBatteryConsumption_ = 0D;
      estimatedDurationMinutes_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Mission_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Mission getDefaultInstanceForType() {
      return com.dronefleet.shared.models.Mission.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Mission build() {
      com.dronefleet.shared.models.Mission result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Mission buildPartial() {
      com.dronefleet.shared.models.Mission result = new com.dronefleet.shared.models.Mission(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dronefleet.shared.models.Mission result) {
      if (routeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          route_ = java.util.Collections.unmodifiableList(route_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.route_ = route_;
      } else {
        result.route_ = routeBuilder_.build();
      }
    }

    private void buildPartial0(com.dronefleet.shared.models.Mission result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.droneId_ = droneId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        orderIds_.makeImmutable();
        result.orderIds_ = orderIds_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.startTime_ = startTimeBuilder_ == null
            ? startTime_
            : startTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.endTime_ = endTimeBuilder_ == null
            ? endTime_
            : endTimeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.estimatedBatteryConsumption_ = estimatedBatteryConsumption_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.estimatedDurationMinutes_ = estimatedDurationMinutes_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.Mission) {
        return mergeFrom((com.dronefleet.shared.models.Mission)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.Mission other) {
      if (other == com.dronefleet.shared.models.Mission.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDroneId().isEmpty()) {
        droneId_ = other.droneId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.orderIds_.isEmpty()) {
        if (orderIds_.isEmpty()) {
          orderIds_ = other.orderIds_;
          bitField0_ |= 0x00000004;
        } else {
          ensureOrderIdsIsMutable();
          orderIds_.addAll(other.orderIds_);
        }
        onChanged();
      }
      if (routeBuilder_ == null) {
        if (!other.route_.isEmpty()) {
          if (route_.isEmpty()) {
            route_ = other.route_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRouteIsMutable();
            route_.addAll(other.route_);
          }
          onChanged();
        }
      } else {
        if (!other.route_.isEmpty()) {
          if (routeBuilder_.isEmpty()) {
            routeBuilder_.dispose();
            routeBuilder_ = null;
            route_ = other.route_;
            bitField0_ = (bitField0_ & ~0x00000008);
            routeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRouteFieldBuilder() : null;
          } else {
            routeBuilder_.addAllMessages(other.route_);
          }
        }
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasStartTime()) {
        mergeStartTime(other.getStartTime());
      }
      if (other.hasEndTime()) {
        mergeEndTime(other.getEndTime());
      }
      if (other.getEstimatedBatteryConsumption() != 0D) {
        setEstimatedBatteryConsumption(other.getEstimatedBatteryConsumption());
      }
      if (other.getEstimatedDurationMinutes() != 0D) {
        setEstimatedDurationMinutes(other.getEstimatedDurationMinutes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              droneId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOrderIdsIsMutable();
              orderIds_.add(s);
              break;
            } // case 26
            case 34: {
              com.dronefleet.shared.models.Waypoint m =
                  input.readMessage(
                      com.dronefleet.shared.models.Waypoint.parser(),
                      extensionRegistry);
              if (routeBuilder_ == null) {
                ensureRouteIsMutable();
                route_.add(m);
              } else {
                routeBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getStartTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getEndTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 65: {
              estimatedBatteryConsumption_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              estimatedDurationMinutes_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object droneId_ = "";
    /**
     * <code>string drone_id = 2 [json_name = "droneId"];</code>
     * @return The droneId.
     */
    public java.lang.String getDroneId() {
      java.lang.Object ref = droneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        droneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drone_id = 2 [json_name = "droneId"];</code>
     * @return The bytes for droneId.
     */
    public com.google.protobuf.ByteString
        getDroneIdBytes() {
      java.lang.Object ref = droneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        droneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drone_id = 2 [json_name = "droneId"];</code>
     * @param value The droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      droneId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 2 [json_name = "droneId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDroneId() {
      droneId_ = getDefaultInstance().getDroneId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 2 [json_name = "droneId"];</code>
     * @param value The bytes for droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      droneId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList orderIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOrderIdsIsMutable() {
      if (!orderIds_.isModifiable()) {
        orderIds_ = new com.google.protobuf.LazyStringArrayList(orderIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @return A list containing the orderIds.
     */
    public com.google.protobuf.ProtocolStringList
        getOrderIdsList() {
      orderIds_.makeImmutable();
      return orderIds_;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @return The count of orderIds.
     */
    public int getOrderIdsCount() {
      return orderIds_.size();
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param index The index of the element to return.
     * @return The orderIds at the given index.
     */
    public java.lang.String getOrderIds(int index) {
      return orderIds_.get(index);
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the orderIds at the given index.
     */
    public com.google.protobuf.ByteString
        getOrderIdsBytes(int index) {
      return orderIds_.getByteString(index);
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param index The index to set the value at.
     * @param value The orderIds to set.
     * @return This builder for chaining.
     */
    public Builder setOrderIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOrderIdsIsMutable();
      orderIds_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param value The orderIds to add.
     * @return This builder for chaining.
     */
    public Builder addOrderIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOrderIdsIsMutable();
      orderIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param values The orderIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrderIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureOrderIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, orderIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderIds() {
      orderIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string order_ids = 3 [json_name = "orderIds"];</code>
     * @param value The bytes of the orderIds to add.
     * @return This builder for chaining.
     */
    public Builder addOrderIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOrderIdsIsMutable();
      orderIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.dronefleet.shared.models.Waypoint> route_ =
      java.util.Collections.emptyList();
    private void ensureRouteIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        route_ = new java.util.ArrayList<com.dronefleet.shared.models.Waypoint>(route_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Waypoint, com.dronefleet.shared.models.Waypoint.Builder, com.dronefleet.shared.models.WaypointOrBuilder> routeBuilder_;

    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Waypoint> getRouteList() {
      if (routeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(route_);
      } else {
        return routeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public int getRouteCount() {
      if (routeBuilder_ == null) {
        return route_.size();
      } else {
        return routeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public com.dronefleet.shared.models.Waypoint getRoute(int index) {
      if (routeBuilder_ == null) {
        return route_.get(index);
      } else {
        return routeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder setRoute(
        int index, com.dronefleet.shared.models.Waypoint value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.set(index, value);
        onChanged();
      } else {
        routeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder setRoute(
        int index, com.dronefleet.shared.models.Waypoint.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.set(index, builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder addRoute(com.dronefleet.shared.models.Waypoint value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.add(value);
        onChanged();
      } else {
        routeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder addRoute(
        int index, com.dronefleet.shared.models.Waypoint value) {
      if (routeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRouteIsMutable();
        route_.add(index, value);
        onChanged();
      } else {
        routeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder addRoute(
        com.dronefleet.shared.models.Waypoint.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.add(builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder addRoute(
        int index, com.dronefleet.shared.models.Waypoint.Builder builderForValue) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.add(index, builderForValue.build());
        onChanged();
      } else {
        routeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder addAllRoute(
        java.lang.Iterable<? extends com.dronefleet.shared.models.Waypoint> values) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, route_);
        onChanged();
      } else {
        routeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder clearRoute() {
      if (routeBuilder_ == null) {
        route_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        routeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public Builder removeRoute(int index) {
      if (routeBuilder_ == null) {
        ensureRouteIsMutable();
        route_.remove(index);
        onChanged();
      } else {
        routeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public com.dronefleet.shared.models.Waypoint.Builder getRouteBuilder(
        int index) {
      return getRouteFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public com.dronefleet.shared.models.WaypointOrBuilder getRouteOrBuilder(
        int index) {
      if (routeBuilder_ == null) {
        return route_.get(index);  } else {
        return routeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public java.util.List<? extends com.dronefleet.shared.models.WaypointOrBuilder> 
         getRouteOrBuilderList() {
      if (routeBuilder_ != null) {
        return routeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(route_);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public com.dronefleet.shared.models.Waypoint.Builder addRouteBuilder() {
      return getRouteFieldBuilder().addBuilder(
          com.dronefleet.shared.models.Waypoint.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public com.dronefleet.shared.models.Waypoint.Builder addRouteBuilder(
        int index) {
      return getRouteFieldBuilder().addBuilder(
          index, com.dronefleet.shared.models.Waypoint.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Waypoint route = 4 [json_name = "route"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Waypoint.Builder> 
         getRouteBuilderList() {
      return getRouteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Waypoint, com.dronefleet.shared.models.Waypoint.Builder, com.dronefleet.shared.models.WaypointOrBuilder> 
        getRouteFieldBuilder() {
      if (routeBuilder_ == null) {
        routeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dronefleet.shared.models.Waypoint, com.dronefleet.shared.models.Waypoint.Builder, com.dronefleet.shared.models.WaypointOrBuilder>(
                route_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        route_ = null;
      }
      return routeBuilder_;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * ACTIVE, COMPLETED, FAILED
     * </pre>
     *
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, FAILED
     * </pre>
     *
     * <code>string status = 5 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, FAILED
     * </pre>
     *
     * <code>string status = 5 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, FAILED
     * </pre>
     *
     * <code>string status = 5 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, FAILED
     * </pre>
     *
     * <code>string status = 5 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp startTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     * @return Whether the startTime field is set.
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     * @return The startTime.
     */
    public com.google.protobuf.Timestamp getStartTime() {
      if (startTimeBuilder_ == null) {
        return startTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
      } else {
        return startTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public Builder setStartTime(com.google.protobuf.Timestamp value) {
      if (startTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startTime_ = value;
      } else {
        startTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public Builder setStartTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startTimeBuilder_ == null) {
        startTime_ = builderForValue.build();
      } else {
        startTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public Builder mergeStartTime(com.google.protobuf.Timestamp value) {
      if (startTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          startTime_ != null &&
          startTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getStartTimeBuilder().mergeFrom(value);
        } else {
          startTime_ = value;
        }
      } else {
        startTimeBuilder_.mergeFrom(value);
      }
      if (startTime_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      startTime_ = null;
      if (startTimeBuilder_ != null) {
        startTimeBuilder_.dispose();
        startTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartTimeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getStartTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder() {
      if (startTimeBuilder_ != null) {
        return startTimeBuilder_.getMessageOrBuilder();
      } else {
        return startTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_time = 6 [json_name = "startTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartTimeFieldBuilder() {
      if (startTimeBuilder_ == null) {
        startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartTime(),
                getParentForChildren(),
                isClean());
        startTime_ = null;
      }
      return startTimeBuilder_;
    }

    private com.google.protobuf.Timestamp endTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     * @return Whether the endTime field is set.
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     * @return The endTime.
     */
    public com.google.protobuf.Timestamp getEndTime() {
      if (endTimeBuilder_ == null) {
        return endTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
      } else {
        return endTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public Builder setEndTime(com.google.protobuf.Timestamp value) {
      if (endTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endTime_ = value;
      } else {
        endTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public Builder setEndTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endTimeBuilder_ == null) {
        endTime_ = builderForValue.build();
      } else {
        endTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public Builder mergeEndTime(com.google.protobuf.Timestamp value) {
      if (endTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          endTime_ != null &&
          endTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getEndTimeBuilder().mergeFrom(value);
        } else {
          endTime_ = value;
        }
      } else {
        endTimeBuilder_.mergeFrom(value);
      }
      if (endTime_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      endTime_ = null;
      if (endTimeBuilder_ != null) {
        endTimeBuilder_.dispose();
        endTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndTimeBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getEndTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder() {
      if (endTimeBuilder_ != null) {
        return endTimeBuilder_.getMessageOrBuilder();
      } else {
        return endTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end_time = 7 [json_name = "endTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndTimeFieldBuilder() {
      if (endTimeBuilder_ == null) {
        endTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndTime(),
                getParentForChildren(),
                isClean());
        endTime_ = null;
      }
      return endTimeBuilder_;
    }

    private double estimatedBatteryConsumption_ ;
    /**
     * <code>double estimated_battery_consumption = 8 [json_name = "estimatedBatteryConsumption"];</code>
     * @return The estimatedBatteryConsumption.
     */
    @java.lang.Override
    public double getEstimatedBatteryConsumption() {
      return estimatedBatteryConsumption_;
    }
    /**
     * <code>double estimated_battery_consumption = 8 [json_name = "estimatedBatteryConsumption"];</code>
     * @param value The estimatedBatteryConsumption to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedBatteryConsumption(double value) {

      estimatedBatteryConsumption_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double estimated_battery_consumption = 8 [json_name = "estimatedBatteryConsumption"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedBatteryConsumption() {
      bitField0_ = (bitField0_ & ~0x00000080);
      estimatedBatteryConsumption_ = 0D;
      onChanged();
      return this;
    }

    private double estimatedDurationMinutes_ ;
    /**
     * <code>double estimated_duration_minutes = 9 [json_name = "estimatedDurationMinutes"];</code>
     * @return The estimatedDurationMinutes.
     */
    @java.lang.Override
    public double getEstimatedDurationMinutes() {
      return estimatedDurationMinutes_;
    }
    /**
     * <code>double estimated_duration_minutes = 9 [json_name = "estimatedDurationMinutes"];</code>
     * @param value The estimatedDurationMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedDurationMinutes(double value) {

      estimatedDurationMinutes_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>double estimated_duration_minutes = 9 [json_name = "estimatedDurationMinutes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedDurationMinutes() {
      bitField0_ = (bitField0_ & ~0x00000100);
      estimatedDurationMinutes_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.Mission)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.Mission)
  private static final com.dronefleet.shared.models.Mission DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.Mission();
  }

  public static com.dronefleet.shared.models.Mission getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mission>
      PARSER = new com.google.protobuf.AbstractParser<Mission>() {
    @java.lang.Override
    public Mission parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Mission> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mission> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.Mission getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

