// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/mission.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class MissionProto {
  private MissionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Waypoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Waypoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Mission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Mission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_MissionAssignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_MissionAssignment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033dronefleet/v1/mission.proto\022\rdroneflee" +
      "t.v1\032\032dronefleet/v1/common.proto\032\037google" +
      "/protobuf/timestamp.proto\"\314\001\n\010Waypoint\022/" +
      "\n\004type\030\001 \001(\0162\033.dronefleet.v1.WaypointTyp" +
      "eR\004type\0223\n\010position\030\002 \001(\0132\027.dronefleet.v" +
      "1.PositionR\010position\022(\n\020related_order_id" +
      "\030\003 \001(\tR\016relatedOrderId\0220\n\024related_wareho" +
      "use_id\030\004 \001(\tR\022relatedWarehouseId\"\214\003\n\007Mis" +
      "sion\022\016\n\002id\030\001 \001(\tR\002id\022\031\n\010drone_id\030\002 \001(\tR\007" +
      "droneId\022\033\n\torder_ids\030\003 \003(\tR\010orderIds\022-\n\005" +
      "route\030\004 \003(\0132\027.dronefleet.v1.WaypointR\005ro" +
      "ute\022\026\n\006status\030\005 \001(\tR\006status\0229\n\nstart_tim" +
      "e\030\006 \001(\0132\032.google.protobuf.TimestampR\tsta" +
      "rtTime\0225\n\010end_time\030\007 \001(\0132\032.google.protob" +
      "uf.TimestampR\007endTime\022B\n\035estimated_batte" +
      "ry_consumption\030\010 \001(\001R\033estimatedBatteryCo" +
      "nsumption\022<\n\032estimated_duration_minutes\030" +
      "\t \001(\001R\030estimatedDurationMinutes\"\374\001\n\021Miss" +
      "ionAssignment\022\031\n\010drone_id\030\001 \001(\tR\007droneId" +
      "\022\033\n\torder_ids\030\002 \003(\tR\010orderIds\022-\n\005route\030\003" +
      " \003(\0132\027.dronefleet.v1.WaypointR\005route\022B\n\035" +
      "estimated_battery_consumption\030\004 \001(\001R\033est" +
      "imatedBatteryConsumption\022<\n\032estimated_du" +
      "ration_minutes\030\005 \001(\001R\030estimatedDurationM" +
      "inutesB\201\001\n\034com.dronefleet.shared.modelsB" +
      "\014MissionProtoP\001\242\002\003DXX\252\002\rDronefleet.V1\312\002\r" +
      "Dronefleet\\V1\342\002\031Dronefleet\\V1\\GPBMetadat" +
      "a\352\002\016Dronefleet::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dronefleet.shared.models.CommonProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_dronefleet_v1_Waypoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_Waypoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Waypoint_descriptor,
        new java.lang.String[] { "Type", "Position", "RelatedOrderId", "RelatedWarehouseId", });
    internal_static_dronefleet_v1_Mission_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dronefleet_v1_Mission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Mission_descriptor,
        new java.lang.String[] { "Id", "DroneId", "OrderIds", "Route", "Status", "StartTime", "EndTime", "EstimatedBatteryConsumption", "EstimatedDurationMinutes", });
    internal_static_dronefleet_v1_MissionAssignment_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dronefleet_v1_MissionAssignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_MissionAssignment_descriptor,
        new java.lang.String[] { "DroneId", "OrderIds", "Route", "EstimatedBatteryConsumption", "EstimatedDurationMinutes", });
    com.dronefleet.shared.models.CommonProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
