// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/mission.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public interface MissionAssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dronefleet.v1.MissionAssignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string drone_id = 1 [json_name = "droneId"];</code>
   * @return The droneId.
   */
  java.lang.String getDroneId();
  /**
   * <code>string drone_id = 1 [json_name = "droneId"];</code>
   * @return The bytes for droneId.
   */
  com.google.protobuf.ByteString
      getDroneIdBytes();

  /**
   * <code>repeated string order_ids = 2 [json_name = "orderIds"];</code>
   * @return A list containing the orderIds.
   */
  java.util.List<java.lang.String>
      getOrderIdsList();
  /**
   * <code>repeated string order_ids = 2 [json_name = "orderIds"];</code>
   * @return The count of orderIds.
   */
  int getOrderIdsCount();
  /**
   * <code>repeated string order_ids = 2 [json_name = "orderIds"];</code>
   * @param index The index of the element to return.
   * @return The orderIds at the given index.
   */
  java.lang.String getOrderIds(int index);
  /**
   * <code>repeated string order_ids = 2 [json_name = "orderIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the orderIds at the given index.
   */
  com.google.protobuf.ByteString
      getOrderIdsBytes(int index);

  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 3 [json_name = "route"];</code>
   */
  java.util.List<com.dronefleet.shared.models.Waypoint> 
      getRouteList();
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 3 [json_name = "route"];</code>
   */
  com.dronefleet.shared.models.Waypoint getRoute(int index);
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 3 [json_name = "route"];</code>
   */
  int getRouteCount();
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 3 [json_name = "route"];</code>
   */
  java.util.List<? extends com.dronefleet.shared.models.WaypointOrBuilder> 
      getRouteOrBuilderList();
  /**
   * <code>repeated .dronefleet.v1.Waypoint route = 3 [json_name = "route"];</code>
   */
  com.dronefleet.shared.models.WaypointOrBuilder getRouteOrBuilder(
      int index);

  /**
   * <code>double estimated_battery_consumption = 4 [json_name = "estimatedBatteryConsumption"];</code>
   * @return The estimatedBatteryConsumption.
   */
  double getEstimatedBatteryConsumption();

  /**
   * <code>double estimated_duration_minutes = 5 [json_name = "estimatedDurationMinutes"];</code>
   * @return The estimatedDurationMinutes.
   */
  double getEstimatedDurationMinutes();
}
