// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/snapshot.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.OptimizationSnapshot}
 */
public final class OptimizationSnapshot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.OptimizationSnapshot)
    OptimizationSnapshotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OptimizationSnapshot.newBuilder() to construct.
  private OptimizationSnapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OptimizationSnapshot() {
    sessionId_ = "";
    drones_ = java.util.Collections.emptyList();
    orders_ = java.util.Collections.emptyList();
    warehouses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OptimizationSnapshot();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.SnapshotProto.internal_static_dronefleet_v1_OptimizationSnapshot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.SnapshotProto.internal_static_dronefleet_v1_OptimizationSnapshot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.OptimizationSnapshot.class, com.dronefleet.shared.models.OptimizationSnapshot.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int DEPOT_FIELD_NUMBER = 3;
  private com.dronefleet.shared.models.Depot depot_;
  /**
   * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
   * @return Whether the depot field is set.
   */
  @java.lang.Override
  public boolean hasDepot() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
   * @return The depot.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Depot getDepot() {
    return depot_ == null ? com.dronefleet.shared.models.Depot.getDefaultInstance() : depot_;
  }
  /**
   * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.DepotOrBuilder getDepotOrBuilder() {
    return depot_ == null ? com.dronefleet.shared.models.Depot.getDefaultInstance() : depot_;
  }

  public static final int DRONES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.dronefleet.shared.models.Drone> drones_;
  /**
   * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dronefleet.shared.models.Drone> getDronesList() {
    return drones_;
  }
  /**
   * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dronefleet.shared.models.DroneOrBuilder> 
      getDronesOrBuilderList() {
    return drones_;
  }
  /**
   * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
   */
  @java.lang.Override
  public int getDronesCount() {
    return drones_.size();
  }
  /**
   * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Drone getDrones(int index) {
    return drones_.get(index);
  }
  /**
   * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.DroneOrBuilder getDronesOrBuilder(
      int index) {
    return drones_.get(index);
  }

  public static final int ORDERS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.dronefleet.shared.models.Order> orders_;
  /**
   * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dronefleet.shared.models.Order> getOrdersList() {
    return orders_;
  }
  /**
   * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dronefleet.shared.models.OrderOrBuilder> 
      getOrdersOrBuilderList() {
    return orders_;
  }
  /**
   * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
   */
  @java.lang.Override
  public int getOrdersCount() {
    return orders_.size();
  }
  /**
   * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Order getOrders(int index) {
    return orders_.get(index);
  }
  /**
   * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.OrderOrBuilder getOrdersOrBuilder(
      int index) {
    return orders_.get(index);
  }

  public static final int WAREHOUSES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.dronefleet.shared.models.Warehouse> warehouses_;
  /**
   * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
   */
  @java.lang.Override
  public java.util.List<com.dronefleet.shared.models.Warehouse> getWarehousesList() {
    return warehouses_;
  }
  /**
   * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.dronefleet.shared.models.WarehouseOrBuilder> 
      getWarehousesOrBuilderList() {
    return warehouses_;
  }
  /**
   * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
   */
  @java.lang.Override
  public int getWarehousesCount() {
    return warehouses_.size();
  }
  /**
   * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Warehouse getWarehouses(int index) {
    return warehouses_.get(index);
  }
  /**
   * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.WarehouseOrBuilder getWarehousesOrBuilder(
      int index) {
    return warehouses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getDepot());
    }
    for (int i = 0; i < drones_.size(); i++) {
      output.writeMessage(4, drones_.get(i));
    }
    for (int i = 0; i < orders_.size(); i++) {
      output.writeMessage(5, orders_.get(i));
    }
    for (int i = 0; i < warehouses_.size(); i++) {
      output.writeMessage(6, warehouses_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDepot());
    }
    for (int i = 0; i < drones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, drones_.get(i));
    }
    for (int i = 0; i < orders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, orders_.get(i));
    }
    for (int i = 0; i < warehouses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, warehouses_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.OptimizationSnapshot)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.OptimizationSnapshot other = (com.dronefleet.shared.models.OptimizationSnapshot) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasDepot() != other.hasDepot()) return false;
    if (hasDepot()) {
      if (!getDepot()
          .equals(other.getDepot())) return false;
    }
    if (!getDronesList()
        .equals(other.getDronesList())) return false;
    if (!getOrdersList()
        .equals(other.getOrdersList())) return false;
    if (!getWarehousesList()
        .equals(other.getWarehousesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasDepot()) {
      hash = (37 * hash) + DEPOT_FIELD_NUMBER;
      hash = (53 * hash) + getDepot().hashCode();
    }
    if (getDronesCount() > 0) {
      hash = (37 * hash) + DRONES_FIELD_NUMBER;
      hash = (53 * hash) + getDronesList().hashCode();
    }
    if (getOrdersCount() > 0) {
      hash = (37 * hash) + ORDERS_FIELD_NUMBER;
      hash = (53 * hash) + getOrdersList().hashCode();
    }
    if (getWarehousesCount() > 0) {
      hash = (37 * hash) + WAREHOUSES_FIELD_NUMBER;
      hash = (53 * hash) + getWarehousesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.OptimizationSnapshot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.OptimizationSnapshot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.OptimizationSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.OptimizationSnapshot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.OptimizationSnapshot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.OptimizationSnapshot)
      com.dronefleet.shared.models.OptimizationSnapshotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.SnapshotProto.internal_static_dronefleet_v1_OptimizationSnapshot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.SnapshotProto.internal_static_dronefleet_v1_OptimizationSnapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.OptimizationSnapshot.class, com.dronefleet.shared.models.OptimizationSnapshot.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.OptimizationSnapshot.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTimestampFieldBuilder();
        getDepotFieldBuilder();
        getDronesFieldBuilder();
        getOrdersFieldBuilder();
        getWarehousesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      depot_ = null;
      if (depotBuilder_ != null) {
        depotBuilder_.dispose();
        depotBuilder_ = null;
      }
      if (dronesBuilder_ == null) {
        drones_ = java.util.Collections.emptyList();
      } else {
        drones_ = null;
        dronesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (ordersBuilder_ == null) {
        orders_ = java.util.Collections.emptyList();
      } else {
        orders_ = null;
        ordersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (warehousesBuilder_ == null) {
        warehouses_ = java.util.Collections.emptyList();
      } else {
        warehouses_ = null;
        warehousesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.SnapshotProto.internal_static_dronefleet_v1_OptimizationSnapshot_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.OptimizationSnapshot getDefaultInstanceForType() {
      return com.dronefleet.shared.models.OptimizationSnapshot.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.OptimizationSnapshot build() {
      com.dronefleet.shared.models.OptimizationSnapshot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.OptimizationSnapshot buildPartial() {
      com.dronefleet.shared.models.OptimizationSnapshot result = new com.dronefleet.shared.models.OptimizationSnapshot(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.dronefleet.shared.models.OptimizationSnapshot result) {
      if (dronesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          drones_ = java.util.Collections.unmodifiableList(drones_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.drones_ = drones_;
      } else {
        result.drones_ = dronesBuilder_.build();
      }
      if (ordersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          orders_ = java.util.Collections.unmodifiableList(orders_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.orders_ = orders_;
      } else {
        result.orders_ = ordersBuilder_.build();
      }
      if (warehousesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          warehouses_ = java.util.Collections.unmodifiableList(warehouses_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.warehouses_ = warehouses_;
      } else {
        result.warehouses_ = warehousesBuilder_.build();
      }
    }

    private void buildPartial0(com.dronefleet.shared.models.OptimizationSnapshot result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.depot_ = depotBuilder_ == null
            ? depot_
            : depotBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.OptimizationSnapshot) {
        return mergeFrom((com.dronefleet.shared.models.OptimizationSnapshot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.OptimizationSnapshot other) {
      if (other == com.dronefleet.shared.models.OptimizationSnapshot.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasDepot()) {
        mergeDepot(other.getDepot());
      }
      if (dronesBuilder_ == null) {
        if (!other.drones_.isEmpty()) {
          if (drones_.isEmpty()) {
            drones_ = other.drones_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDronesIsMutable();
            drones_.addAll(other.drones_);
          }
          onChanged();
        }
      } else {
        if (!other.drones_.isEmpty()) {
          if (dronesBuilder_.isEmpty()) {
            dronesBuilder_.dispose();
            dronesBuilder_ = null;
            drones_ = other.drones_;
            bitField0_ = (bitField0_ & ~0x00000008);
            dronesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDronesFieldBuilder() : null;
          } else {
            dronesBuilder_.addAllMessages(other.drones_);
          }
        }
      }
      if (ordersBuilder_ == null) {
        if (!other.orders_.isEmpty()) {
          if (orders_.isEmpty()) {
            orders_ = other.orders_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureOrdersIsMutable();
            orders_.addAll(other.orders_);
          }
          onChanged();
        }
      } else {
        if (!other.orders_.isEmpty()) {
          if (ordersBuilder_.isEmpty()) {
            ordersBuilder_.dispose();
            ordersBuilder_ = null;
            orders_ = other.orders_;
            bitField0_ = (bitField0_ & ~0x00000010);
            ordersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrdersFieldBuilder() : null;
          } else {
            ordersBuilder_.addAllMessages(other.orders_);
          }
        }
      }
      if (warehousesBuilder_ == null) {
        if (!other.warehouses_.isEmpty()) {
          if (warehouses_.isEmpty()) {
            warehouses_ = other.warehouses_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureWarehousesIsMutable();
            warehouses_.addAll(other.warehouses_);
          }
          onChanged();
        }
      } else {
        if (!other.warehouses_.isEmpty()) {
          if (warehousesBuilder_.isEmpty()) {
            warehousesBuilder_.dispose();
            warehousesBuilder_ = null;
            warehouses_ = other.warehouses_;
            bitField0_ = (bitField0_ & ~0x00000020);
            warehousesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWarehousesFieldBuilder() : null;
          } else {
            warehousesBuilder_.addAllMessages(other.warehouses_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDepotFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.dronefleet.shared.models.Drone m =
                  input.readMessage(
                      com.dronefleet.shared.models.Drone.parser(),
                      extensionRegistry);
              if (dronesBuilder_ == null) {
                ensureDronesIsMutable();
                drones_.add(m);
              } else {
                dronesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.dronefleet.shared.models.Order m =
                  input.readMessage(
                      com.dronefleet.shared.models.Order.parser(),
                      extensionRegistry);
              if (ordersBuilder_ == null) {
                ensureOrdersIsMutable();
                orders_.add(m);
              } else {
                ordersBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.dronefleet.shared.models.Warehouse m =
                  input.readMessage(
                      com.dronefleet.shared.models.Warehouse.parser(),
                      extensionRegistry);
              if (warehousesBuilder_ == null) {
                ensureWarehousesIsMutable();
                warehouses_.add(m);
              } else {
                warehousesBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.dronefleet.shared.models.Depot depot_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Depot, com.dronefleet.shared.models.Depot.Builder, com.dronefleet.shared.models.DepotOrBuilder> depotBuilder_;
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     * @return Whether the depot field is set.
     */
    public boolean hasDepot() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     * @return The depot.
     */
    public com.dronefleet.shared.models.Depot getDepot() {
      if (depotBuilder_ == null) {
        return depot_ == null ? com.dronefleet.shared.models.Depot.getDefaultInstance() : depot_;
      } else {
        return depotBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public Builder setDepot(com.dronefleet.shared.models.Depot value) {
      if (depotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        depot_ = value;
      } else {
        depotBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public Builder setDepot(
        com.dronefleet.shared.models.Depot.Builder builderForValue) {
      if (depotBuilder_ == null) {
        depot_ = builderForValue.build();
      } else {
        depotBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public Builder mergeDepot(com.dronefleet.shared.models.Depot value) {
      if (depotBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          depot_ != null &&
          depot_ != com.dronefleet.shared.models.Depot.getDefaultInstance()) {
          getDepotBuilder().mergeFrom(value);
        } else {
          depot_ = value;
        }
      } else {
        depotBuilder_.mergeFrom(value);
      }
      if (depot_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public Builder clearDepot() {
      bitField0_ = (bitField0_ & ~0x00000004);
      depot_ = null;
      if (depotBuilder_ != null) {
        depotBuilder_.dispose();
        depotBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public com.dronefleet.shared.models.Depot.Builder getDepotBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDepotFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    public com.dronefleet.shared.models.DepotOrBuilder getDepotOrBuilder() {
      if (depotBuilder_ != null) {
        return depotBuilder_.getMessageOrBuilder();
      } else {
        return depot_ == null ?
            com.dronefleet.shared.models.Depot.getDefaultInstance() : depot_;
      }
    }
    /**
     * <code>.dronefleet.v1.Depot depot = 3 [json_name = "depot"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Depot, com.dronefleet.shared.models.Depot.Builder, com.dronefleet.shared.models.DepotOrBuilder> 
        getDepotFieldBuilder() {
      if (depotBuilder_ == null) {
        depotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Depot, com.dronefleet.shared.models.Depot.Builder, com.dronefleet.shared.models.DepotOrBuilder>(
                getDepot(),
                getParentForChildren(),
                isClean());
        depot_ = null;
      }
      return depotBuilder_;
    }

    private java.util.List<com.dronefleet.shared.models.Drone> drones_ =
      java.util.Collections.emptyList();
    private void ensureDronesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        drones_ = new java.util.ArrayList<com.dronefleet.shared.models.Drone>(drones_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Drone, com.dronefleet.shared.models.Drone.Builder, com.dronefleet.shared.models.DroneOrBuilder> dronesBuilder_;

    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Drone> getDronesList() {
      if (dronesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(drones_);
      } else {
        return dronesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public int getDronesCount() {
      if (dronesBuilder_ == null) {
        return drones_.size();
      } else {
        return dronesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public com.dronefleet.shared.models.Drone getDrones(int index) {
      if (dronesBuilder_ == null) {
        return drones_.get(index);
      } else {
        return dronesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder setDrones(
        int index, com.dronefleet.shared.models.Drone value) {
      if (dronesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDronesIsMutable();
        drones_.set(index, value);
        onChanged();
      } else {
        dronesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder setDrones(
        int index, com.dronefleet.shared.models.Drone.Builder builderForValue) {
      if (dronesBuilder_ == null) {
        ensureDronesIsMutable();
        drones_.set(index, builderForValue.build());
        onChanged();
      } else {
        dronesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder addDrones(com.dronefleet.shared.models.Drone value) {
      if (dronesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDronesIsMutable();
        drones_.add(value);
        onChanged();
      } else {
        dronesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder addDrones(
        int index, com.dronefleet.shared.models.Drone value) {
      if (dronesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDronesIsMutable();
        drones_.add(index, value);
        onChanged();
      } else {
        dronesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder addDrones(
        com.dronefleet.shared.models.Drone.Builder builderForValue) {
      if (dronesBuilder_ == null) {
        ensureDronesIsMutable();
        drones_.add(builderForValue.build());
        onChanged();
      } else {
        dronesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder addDrones(
        int index, com.dronefleet.shared.models.Drone.Builder builderForValue) {
      if (dronesBuilder_ == null) {
        ensureDronesIsMutable();
        drones_.add(index, builderForValue.build());
        onChanged();
      } else {
        dronesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder addAllDrones(
        java.lang.Iterable<? extends com.dronefleet.shared.models.Drone> values) {
      if (dronesBuilder_ == null) {
        ensureDronesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drones_);
        onChanged();
      } else {
        dronesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder clearDrones() {
      if (dronesBuilder_ == null) {
        drones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        dronesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public Builder removeDrones(int index) {
      if (dronesBuilder_ == null) {
        ensureDronesIsMutable();
        drones_.remove(index);
        onChanged();
      } else {
        dronesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public com.dronefleet.shared.models.Drone.Builder getDronesBuilder(
        int index) {
      return getDronesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public com.dronefleet.shared.models.DroneOrBuilder getDronesOrBuilder(
        int index) {
      if (dronesBuilder_ == null) {
        return drones_.get(index);  } else {
        return dronesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public java.util.List<? extends com.dronefleet.shared.models.DroneOrBuilder> 
         getDronesOrBuilderList() {
      if (dronesBuilder_ != null) {
        return dronesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(drones_);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public com.dronefleet.shared.models.Drone.Builder addDronesBuilder() {
      return getDronesFieldBuilder().addBuilder(
          com.dronefleet.shared.models.Drone.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public com.dronefleet.shared.models.Drone.Builder addDronesBuilder(
        int index) {
      return getDronesFieldBuilder().addBuilder(
          index, com.dronefleet.shared.models.Drone.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Drone drones = 4 [json_name = "drones"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Drone.Builder> 
         getDronesBuilderList() {
      return getDronesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Drone, com.dronefleet.shared.models.Drone.Builder, com.dronefleet.shared.models.DroneOrBuilder> 
        getDronesFieldBuilder() {
      if (dronesBuilder_ == null) {
        dronesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dronefleet.shared.models.Drone, com.dronefleet.shared.models.Drone.Builder, com.dronefleet.shared.models.DroneOrBuilder>(
                drones_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        drones_ = null;
      }
      return dronesBuilder_;
    }

    private java.util.List<com.dronefleet.shared.models.Order> orders_ =
      java.util.Collections.emptyList();
    private void ensureOrdersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        orders_ = new java.util.ArrayList<com.dronefleet.shared.models.Order>(orders_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Order, com.dronefleet.shared.models.Order.Builder, com.dronefleet.shared.models.OrderOrBuilder> ordersBuilder_;

    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Order> getOrdersList() {
      if (ordersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orders_);
      } else {
        return ordersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public int getOrdersCount() {
      if (ordersBuilder_ == null) {
        return orders_.size();
      } else {
        return ordersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public com.dronefleet.shared.models.Order getOrders(int index) {
      if (ordersBuilder_ == null) {
        return orders_.get(index);
      } else {
        return ordersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder setOrders(
        int index, com.dronefleet.shared.models.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.set(index, value);
        onChanged();
      } else {
        ordersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder setOrders(
        int index, com.dronefleet.shared.models.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.set(index, builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder addOrders(com.dronefleet.shared.models.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.add(value);
        onChanged();
      } else {
        ordersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder addOrders(
        int index, com.dronefleet.shared.models.Order value) {
      if (ordersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrdersIsMutable();
        orders_.add(index, value);
        onChanged();
      } else {
        ordersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder addOrders(
        com.dronefleet.shared.models.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.add(builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder addOrders(
        int index, com.dronefleet.shared.models.Order.Builder builderForValue) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.add(index, builderForValue.build());
        onChanged();
      } else {
        ordersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder addAllOrders(
        java.lang.Iterable<? extends com.dronefleet.shared.models.Order> values) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orders_);
        onChanged();
      } else {
        ordersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder clearOrders() {
      if (ordersBuilder_ == null) {
        orders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        ordersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public Builder removeOrders(int index) {
      if (ordersBuilder_ == null) {
        ensureOrdersIsMutable();
        orders_.remove(index);
        onChanged();
      } else {
        ordersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public com.dronefleet.shared.models.Order.Builder getOrdersBuilder(
        int index) {
      return getOrdersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public com.dronefleet.shared.models.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      if (ordersBuilder_ == null) {
        return orders_.get(index);  } else {
        return ordersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public java.util.List<? extends com.dronefleet.shared.models.OrderOrBuilder> 
         getOrdersOrBuilderList() {
      if (ordersBuilder_ != null) {
        return ordersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orders_);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public com.dronefleet.shared.models.Order.Builder addOrdersBuilder() {
      return getOrdersFieldBuilder().addBuilder(
          com.dronefleet.shared.models.Order.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public com.dronefleet.shared.models.Order.Builder addOrdersBuilder(
        int index) {
      return getOrdersFieldBuilder().addBuilder(
          index, com.dronefleet.shared.models.Order.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Order orders = 5 [json_name = "orders"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Order.Builder> 
         getOrdersBuilderList() {
      return getOrdersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Order, com.dronefleet.shared.models.Order.Builder, com.dronefleet.shared.models.OrderOrBuilder> 
        getOrdersFieldBuilder() {
      if (ordersBuilder_ == null) {
        ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dronefleet.shared.models.Order, com.dronefleet.shared.models.Order.Builder, com.dronefleet.shared.models.OrderOrBuilder>(
                orders_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        orders_ = null;
      }
      return ordersBuilder_;
    }

    private java.util.List<com.dronefleet.shared.models.Warehouse> warehouses_ =
      java.util.Collections.emptyList();
    private void ensureWarehousesIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        warehouses_ = new java.util.ArrayList<com.dronefleet.shared.models.Warehouse>(warehouses_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Warehouse, com.dronefleet.shared.models.Warehouse.Builder, com.dronefleet.shared.models.WarehouseOrBuilder> warehousesBuilder_;

    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Warehouse> getWarehousesList() {
      if (warehousesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(warehouses_);
      } else {
        return warehousesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public int getWarehousesCount() {
      if (warehousesBuilder_ == null) {
        return warehouses_.size();
      } else {
        return warehousesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public com.dronefleet.shared.models.Warehouse getWarehouses(int index) {
      if (warehousesBuilder_ == null) {
        return warehouses_.get(index);
      } else {
        return warehousesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder setWarehouses(
        int index, com.dronefleet.shared.models.Warehouse value) {
      if (warehousesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWarehousesIsMutable();
        warehouses_.set(index, value);
        onChanged();
      } else {
        warehousesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder setWarehouses(
        int index, com.dronefleet.shared.models.Warehouse.Builder builderForValue) {
      if (warehousesBuilder_ == null) {
        ensureWarehousesIsMutable();
        warehouses_.set(index, builderForValue.build());
        onChanged();
      } else {
        warehousesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder addWarehouses(com.dronefleet.shared.models.Warehouse value) {
      if (warehousesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWarehousesIsMutable();
        warehouses_.add(value);
        onChanged();
      } else {
        warehousesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder addWarehouses(
        int index, com.dronefleet.shared.models.Warehouse value) {
      if (warehousesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWarehousesIsMutable();
        warehouses_.add(index, value);
        onChanged();
      } else {
        warehousesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder addWarehouses(
        com.dronefleet.shared.models.Warehouse.Builder builderForValue) {
      if (warehousesBuilder_ == null) {
        ensureWarehousesIsMutable();
        warehouses_.add(builderForValue.build());
        onChanged();
      } else {
        warehousesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder addWarehouses(
        int index, com.dronefleet.shared.models.Warehouse.Builder builderForValue) {
      if (warehousesBuilder_ == null) {
        ensureWarehousesIsMutable();
        warehouses_.add(index, builderForValue.build());
        onChanged();
      } else {
        warehousesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder addAllWarehouses(
        java.lang.Iterable<? extends com.dronefleet.shared.models.Warehouse> values) {
      if (warehousesBuilder_ == null) {
        ensureWarehousesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, warehouses_);
        onChanged();
      } else {
        warehousesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder clearWarehouses() {
      if (warehousesBuilder_ == null) {
        warehouses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        warehousesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public Builder removeWarehouses(int index) {
      if (warehousesBuilder_ == null) {
        ensureWarehousesIsMutable();
        warehouses_.remove(index);
        onChanged();
      } else {
        warehousesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public com.dronefleet.shared.models.Warehouse.Builder getWarehousesBuilder(
        int index) {
      return getWarehousesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public com.dronefleet.shared.models.WarehouseOrBuilder getWarehousesOrBuilder(
        int index) {
      if (warehousesBuilder_ == null) {
        return warehouses_.get(index);  } else {
        return warehousesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public java.util.List<? extends com.dronefleet.shared.models.WarehouseOrBuilder> 
         getWarehousesOrBuilderList() {
      if (warehousesBuilder_ != null) {
        return warehousesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(warehouses_);
      }
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public com.dronefleet.shared.models.Warehouse.Builder addWarehousesBuilder() {
      return getWarehousesFieldBuilder().addBuilder(
          com.dronefleet.shared.models.Warehouse.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public com.dronefleet.shared.models.Warehouse.Builder addWarehousesBuilder(
        int index) {
      return getWarehousesFieldBuilder().addBuilder(
          index, com.dronefleet.shared.models.Warehouse.getDefaultInstance());
    }
    /**
     * <code>repeated .dronefleet.v1.Warehouse warehouses = 6 [json_name = "warehouses"];</code>
     */
    public java.util.List<com.dronefleet.shared.models.Warehouse.Builder> 
         getWarehousesBuilderList() {
      return getWarehousesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dronefleet.shared.models.Warehouse, com.dronefleet.shared.models.Warehouse.Builder, com.dronefleet.shared.models.WarehouseOrBuilder> 
        getWarehousesFieldBuilder() {
      if (warehousesBuilder_ == null) {
        warehousesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dronefleet.shared.models.Warehouse, com.dronefleet.shared.models.Warehouse.Builder, com.dronefleet.shared.models.WarehouseOrBuilder>(
                warehouses_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        warehouses_ = null;
      }
      return warehousesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.OptimizationSnapshot)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.OptimizationSnapshot)
  private static final com.dronefleet.shared.models.OptimizationSnapshot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.OptimizationSnapshot();
  }

  public static com.dronefleet.shared.models.OptimizationSnapshot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OptimizationSnapshot>
      PARSER = new com.google.protobuf.AbstractParser<OptimizationSnapshot>() {
    @java.lang.Override
    public OptimizationSnapshot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OptimizationSnapshot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OptimizationSnapshot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.OptimizationSnapshot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

