// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf enum {@code dronefleet.v1.OrderPriority}
 */
public enum OrderPriority
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ORDER_PRIORITY_UNSPECIFIED = 0;</code>
   */
  ORDER_PRIORITY_UNSPECIFIED(0),
  /**
   * <code>ORDER_PRIORITY_STANDARD = 1;</code>
   */
  ORDER_PRIORITY_STANDARD(1),
  /**
   * <code>ORDER_PRIORITY_HIGH = 2;</code>
   */
  ORDER_PRIORITY_HIGH(2),
  /**
   * <code>ORDER_PRIORITY_CRITICAL = 3;</code>
   */
  ORDER_PRIORITY_CRITICAL(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ORDER_PRIORITY_UNSPECIFIED = 0;</code>
   */
  public static final int ORDER_PRIORITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ORDER_PRIORITY_STANDARD = 1;</code>
   */
  public static final int ORDER_PRIORITY_STANDARD_VALUE = 1;
  /**
   * <code>ORDER_PRIORITY_HIGH = 2;</code>
   */
  public static final int ORDER_PRIORITY_HIGH_VALUE = 2;
  /**
   * <code>ORDER_PRIORITY_CRITICAL = 3;</code>
   */
  public static final int ORDER_PRIORITY_CRITICAL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderPriority valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderPriority forNumber(int value) {
    switch (value) {
      case 0: return ORDER_PRIORITY_UNSPECIFIED;
      case 1: return ORDER_PRIORITY_STANDARD;
      case 2: return ORDER_PRIORITY_HIGH;
      case 3: return ORDER_PRIORITY_CRITICAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderPriority>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderPriority> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderPriority>() {
          public OrderPriority findValueByNumber(int number) {
            return OrderPriority.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dronefleet.shared.models.CommonProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final OrderPriority[] VALUES = values();

  public static OrderPriority valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderPriority(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dronefleet.v1.OrderPriority)
}

