// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/order.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.Order}
 */
public final class Order extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.Order)
    OrderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Order.newBuilder() to construct.
  private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Order() {
    id_ = "";
    status_ = 0;
    priority_ = 0;
    productType_ = "";
    assignedDroneId_ = "";
    assignedMissionId_ = "";
    solvingSessionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Order();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.OrderProto.internal_static_dronefleet_v1_Order_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.OrderProto.internal_static_dronefleet_v1_Order_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.Order.class, com.dronefleet.shared.models.Order.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICKUP_LOCATION_FIELD_NUMBER = 2;
  private com.dronefleet.shared.models.Position pickupLocation_;
  /**
   * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
   * @return Whether the pickupLocation field is set.
   */
  @java.lang.Override
  public boolean hasPickupLocation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
   * @return The pickupLocation.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Position getPickupLocation() {
    return pickupLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : pickupLocation_;
  }
  /**
   * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.PositionOrBuilder getPickupLocationOrBuilder() {
    return pickupLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : pickupLocation_;
  }

  public static final int DELIVERY_LOCATION_FIELD_NUMBER = 3;
  private com.dronefleet.shared.models.Position deliveryLocation_;
  /**
   * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
   * @return Whether the deliveryLocation field is set.
   */
  @java.lang.Override
  public boolean hasDeliveryLocation() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
   * @return The deliveryLocation.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Position getDeliveryLocation() {
    return deliveryLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : deliveryLocation_;
  }
  /**
   * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.PositionOrBuilder getDeliveryLocationOrBuilder() {
    return deliveryLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : deliveryLocation_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_ = 0;
  /**
   * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.dronefleet.shared.models.OrderStatus getStatus() {
    com.dronefleet.shared.models.OrderStatus result = com.dronefleet.shared.models.OrderStatus.forNumber(status_);
    return result == null ? com.dronefleet.shared.models.OrderStatus.UNRECOGNIZED : result;
  }

  public static final int PRIORITY_FIELD_NUMBER = 5;
  private int priority_ = 0;
  /**
   * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
   * @return The enum numeric value on the wire for priority.
   */
  @java.lang.Override public int getPriorityValue() {
    return priority_;
  }
  /**
   * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
   * @return The priority.
   */
  @java.lang.Override public com.dronefleet.shared.models.OrderPriority getPriority() {
    com.dronefleet.shared.models.OrderPriority result = com.dronefleet.shared.models.OrderPriority.forNumber(priority_);
    return result == null ? com.dronefleet.shared.models.OrderPriority.UNRECOGNIZED : result;
  }

  public static final int PRODUCT_TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productType_ = "";
  /**
   * <code>string product_type = 6 [json_name = "productType"];</code>
   * @return The productType.
   */
  @java.lang.Override
  public java.lang.String getProductType() {
    java.lang.Object ref = productType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productType_ = s;
      return s;
    }
  }
  /**
   * <code>string product_type = 6 [json_name = "productType"];</code>
   * @return The bytes for productType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductTypeBytes() {
    java.lang.Object ref = productType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int ASSIGNED_DRONE_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object assignedDroneId_ = "";
  /**
   * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
   * @return The assignedDroneId.
   */
  @java.lang.Override
  public java.lang.String getAssignedDroneId() {
    java.lang.Object ref = assignedDroneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignedDroneId_ = s;
      return s;
    }
  }
  /**
   * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
   * @return The bytes for assignedDroneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignedDroneIdBytes() {
    java.lang.Object ref = assignedDroneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignedDroneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNED_MISSION_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object assignedMissionId_ = "";
  /**
   * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
   * @return The assignedMissionId.
   */
  @java.lang.Override
  public java.lang.String getAssignedMissionId() {
    java.lang.Object ref = assignedMissionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignedMissionId_ = s;
      return s;
    }
  }
  /**
   * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
   * @return The bytes for assignedMissionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignedMissionIdBytes() {
    java.lang.Object ref = assignedMissionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignedMissionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOLVING_SESSION_ID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object solvingSessionId_ = "";
  /**
   * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
   * @return The solvingSessionId.
   */
  @java.lang.Override
  public java.lang.String getSolvingSessionId() {
    java.lang.Object ref = solvingSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      solvingSessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
   * @return The bytes for solvingSessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSolvingSessionIdBytes() {
    java.lang.Object ref = solvingSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      solvingSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPickupLocation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getDeliveryLocation());
    }
    if (status_ != com.dronefleet.shared.models.OrderStatus.ORDER_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (priority_ != com.dronefleet.shared.models.OrderPriority.ORDER_PRIORITY_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, priority_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, productType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getCreatedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedDroneId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, assignedDroneId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedMissionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, assignedMissionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(solvingSessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, solvingSessionId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPickupLocation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDeliveryLocation());
    }
    if (status_ != com.dronefleet.shared.models.OrderStatus.ORDER_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (priority_ != com.dronefleet.shared.models.OrderPriority.ORDER_PRIORITY_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, priority_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, productType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getCreatedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedDroneId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, assignedDroneId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedMissionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, assignedMissionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(solvingSessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, solvingSessionId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.Order)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.Order other = (com.dronefleet.shared.models.Order) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasPickupLocation() != other.hasPickupLocation()) return false;
    if (hasPickupLocation()) {
      if (!getPickupLocation()
          .equals(other.getPickupLocation())) return false;
    }
    if (hasDeliveryLocation() != other.hasDeliveryLocation()) return false;
    if (hasDeliveryLocation()) {
      if (!getDeliveryLocation()
          .equals(other.getDeliveryLocation())) return false;
    }
    if (status_ != other.status_) return false;
    if (priority_ != other.priority_) return false;
    if (!getProductType()
        .equals(other.getProductType())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!getAssignedDroneId()
        .equals(other.getAssignedDroneId())) return false;
    if (!getAssignedMissionId()
        .equals(other.getAssignedMissionId())) return false;
    if (!getSolvingSessionId()
        .equals(other.getSolvingSessionId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasPickupLocation()) {
      hash = (37 * hash) + PICKUP_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getPickupLocation().hashCode();
    }
    if (hasDeliveryLocation()) {
      hash = (37 * hash) + DELIVERY_LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryLocation().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + priority_;
    hash = (37 * hash) + PRODUCT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProductType().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (37 * hash) + ASSIGNED_DRONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedDroneId().hashCode();
    hash = (37 * hash) + ASSIGNED_MISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedMissionId().hashCode();
    hash = (37 * hash) + SOLVING_SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSolvingSessionId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.Order prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.Order)
      com.dronefleet.shared.models.OrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.OrderProto.internal_static_dronefleet_v1_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.OrderProto.internal_static_dronefleet_v1_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.Order.class, com.dronefleet.shared.models.Order.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.Order.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPickupLocationFieldBuilder();
        getDeliveryLocationFieldBuilder();
        getCreatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      pickupLocation_ = null;
      if (pickupLocationBuilder_ != null) {
        pickupLocationBuilder_.dispose();
        pickupLocationBuilder_ = null;
      }
      deliveryLocation_ = null;
      if (deliveryLocationBuilder_ != null) {
        deliveryLocationBuilder_.dispose();
        deliveryLocationBuilder_ = null;
      }
      status_ = 0;
      priority_ = 0;
      productType_ = "";
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      assignedDroneId_ = "";
      assignedMissionId_ = "";
      solvingSessionId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.OrderProto.internal_static_dronefleet_v1_Order_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Order getDefaultInstanceForType() {
      return com.dronefleet.shared.models.Order.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Order build() {
      com.dronefleet.shared.models.Order result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Order buildPartial() {
      com.dronefleet.shared.models.Order result = new com.dronefleet.shared.models.Order(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dronefleet.shared.models.Order result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pickupLocation_ = pickupLocationBuilder_ == null
            ? pickupLocation_
            : pickupLocationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.deliveryLocation_ = deliveryLocationBuilder_ == null
            ? deliveryLocation_
            : deliveryLocationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.priority_ = priority_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.productType_ = productType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.assignedDroneId_ = assignedDroneId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.assignedMissionId_ = assignedMissionId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.solvingSessionId_ = solvingSessionId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.Order) {
        return mergeFrom((com.dronefleet.shared.models.Order)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.Order other) {
      if (other == com.dronefleet.shared.models.Order.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPickupLocation()) {
        mergePickupLocation(other.getPickupLocation());
      }
      if (other.hasDeliveryLocation()) {
        mergeDeliveryLocation(other.getDeliveryLocation());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.priority_ != 0) {
        setPriorityValue(other.getPriorityValue());
      }
      if (!other.getProductType().isEmpty()) {
        productType_ = other.productType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (!other.getAssignedDroneId().isEmpty()) {
        assignedDroneId_ = other.assignedDroneId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getAssignedMissionId().isEmpty()) {
        assignedMissionId_ = other.assignedMissionId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getSolvingSessionId().isEmpty()) {
        solvingSessionId_ = other.solvingSessionId_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPickupLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDeliveryLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              priority_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              productType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              assignedDroneId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              assignedMissionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              solvingSessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.dronefleet.shared.models.Position pickupLocation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> pickupLocationBuilder_;
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     * @return Whether the pickupLocation field is set.
     */
    public boolean hasPickupLocation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     * @return The pickupLocation.
     */
    public com.dronefleet.shared.models.Position getPickupLocation() {
      if (pickupLocationBuilder_ == null) {
        return pickupLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : pickupLocation_;
      } else {
        return pickupLocationBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public Builder setPickupLocation(com.dronefleet.shared.models.Position value) {
      if (pickupLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pickupLocation_ = value;
      } else {
        pickupLocationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public Builder setPickupLocation(
        com.dronefleet.shared.models.Position.Builder builderForValue) {
      if (pickupLocationBuilder_ == null) {
        pickupLocation_ = builderForValue.build();
      } else {
        pickupLocationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public Builder mergePickupLocation(com.dronefleet.shared.models.Position value) {
      if (pickupLocationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pickupLocation_ != null &&
          pickupLocation_ != com.dronefleet.shared.models.Position.getDefaultInstance()) {
          getPickupLocationBuilder().mergeFrom(value);
        } else {
          pickupLocation_ = value;
        }
      } else {
        pickupLocationBuilder_.mergeFrom(value);
      }
      if (pickupLocation_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public Builder clearPickupLocation() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pickupLocation_ = null;
      if (pickupLocationBuilder_ != null) {
        pickupLocationBuilder_.dispose();
        pickupLocationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public com.dronefleet.shared.models.Position.Builder getPickupLocationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPickupLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    public com.dronefleet.shared.models.PositionOrBuilder getPickupLocationOrBuilder() {
      if (pickupLocationBuilder_ != null) {
        return pickupLocationBuilder_.getMessageOrBuilder();
      } else {
        return pickupLocation_ == null ?
            com.dronefleet.shared.models.Position.getDefaultInstance() : pickupLocation_;
      }
    }
    /**
     * <code>.dronefleet.v1.Position pickup_location = 2 [json_name = "pickupLocation"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> 
        getPickupLocationFieldBuilder() {
      if (pickupLocationBuilder_ == null) {
        pickupLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder>(
                getPickupLocation(),
                getParentForChildren(),
                isClean());
        pickupLocation_ = null;
      }
      return pickupLocationBuilder_;
    }

    private com.dronefleet.shared.models.Position deliveryLocation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> deliveryLocationBuilder_;
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     * @return Whether the deliveryLocation field is set.
     */
    public boolean hasDeliveryLocation() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     * @return The deliveryLocation.
     */
    public com.dronefleet.shared.models.Position getDeliveryLocation() {
      if (deliveryLocationBuilder_ == null) {
        return deliveryLocation_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : deliveryLocation_;
      } else {
        return deliveryLocationBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public Builder setDeliveryLocation(com.dronefleet.shared.models.Position value) {
      if (deliveryLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryLocation_ = value;
      } else {
        deliveryLocationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public Builder setDeliveryLocation(
        com.dronefleet.shared.models.Position.Builder builderForValue) {
      if (deliveryLocationBuilder_ == null) {
        deliveryLocation_ = builderForValue.build();
      } else {
        deliveryLocationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public Builder mergeDeliveryLocation(com.dronefleet.shared.models.Position value) {
      if (deliveryLocationBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          deliveryLocation_ != null &&
          deliveryLocation_ != com.dronefleet.shared.models.Position.getDefaultInstance()) {
          getDeliveryLocationBuilder().mergeFrom(value);
        } else {
          deliveryLocation_ = value;
        }
      } else {
        deliveryLocationBuilder_.mergeFrom(value);
      }
      if (deliveryLocation_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public Builder clearDeliveryLocation() {
      bitField0_ = (bitField0_ & ~0x00000004);
      deliveryLocation_ = null;
      if (deliveryLocationBuilder_ != null) {
        deliveryLocationBuilder_.dispose();
        deliveryLocationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public com.dronefleet.shared.models.Position.Builder getDeliveryLocationBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDeliveryLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    public com.dronefleet.shared.models.PositionOrBuilder getDeliveryLocationOrBuilder() {
      if (deliveryLocationBuilder_ != null) {
        return deliveryLocationBuilder_.getMessageOrBuilder();
      } else {
        return deliveryLocation_ == null ?
            com.dronefleet.shared.models.Position.getDefaultInstance() : deliveryLocation_;
      }
    }
    /**
     * <code>.dronefleet.v1.Position delivery_location = 3 [json_name = "deliveryLocation"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> 
        getDeliveryLocationFieldBuilder() {
      if (deliveryLocationBuilder_ == null) {
        deliveryLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder>(
                getDeliveryLocation(),
                getParentForChildren(),
                isClean());
        deliveryLocation_ = null;
      }
      return deliveryLocationBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.dronefleet.shared.models.OrderStatus getStatus() {
      com.dronefleet.shared.models.OrderStatus result = com.dronefleet.shared.models.OrderStatus.forNumber(status_);
      return result == null ? com.dronefleet.shared.models.OrderStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.dronefleet.shared.models.OrderStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.OrderStatus status = 4 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private int priority_ = 0;
    /**
     * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
     * @return The enum numeric value on the wire for priority.
     */
    @java.lang.Override public int getPriorityValue() {
      return priority_;
    }
    /**
     * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
     * @param value The enum numeric value on the wire for priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriorityValue(int value) {
      priority_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
     * @return The priority.
     */
    @java.lang.Override
    public com.dronefleet.shared.models.OrderPriority getPriority() {
      com.dronefleet.shared.models.OrderPriority result = com.dronefleet.shared.models.OrderPriority.forNumber(priority_);
      return result == null ? com.dronefleet.shared.models.OrderPriority.UNRECOGNIZED : result;
    }
    /**
     * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(com.dronefleet.shared.models.OrderPriority value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      priority_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.OrderPriority priority = 5 [json_name = "priority"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000010);
      priority_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object productType_ = "";
    /**
     * <code>string product_type = 6 [json_name = "productType"];</code>
     * @return The productType.
     */
    public java.lang.String getProductType() {
      java.lang.Object ref = productType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_type = 6 [json_name = "productType"];</code>
     * @return The bytes for productType.
     */
    public com.google.protobuf.ByteString
        getProductTypeBytes() {
      java.lang.Object ref = productType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_type = 6 [json_name = "productType"];</code>
     * @param value The productType to set.
     * @return This builder for chaining.
     */
    public Builder setProductType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string product_type = 6 [json_name = "productType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProductType() {
      productType_ = getDefaultInstance().getProductType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string product_type = 6 [json_name = "productType"];</code>
     * @param value The bytes for productType to set.
     * @return This builder for chaining.
     */
    public Builder setProductTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 7 [json_name = "createdAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private java.lang.Object assignedDroneId_ = "";
    /**
     * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
     * @return The assignedDroneId.
     */
    public java.lang.String getAssignedDroneId() {
      java.lang.Object ref = assignedDroneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignedDroneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
     * @return The bytes for assignedDroneId.
     */
    public com.google.protobuf.ByteString
        getAssignedDroneIdBytes() {
      java.lang.Object ref = assignedDroneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignedDroneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
     * @param value The assignedDroneId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedDroneId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      assignedDroneId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedDroneId() {
      assignedDroneId_ = getDefaultInstance().getAssignedDroneId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_drone_id = 8 [json_name = "assignedDroneId"];</code>
     * @param value The bytes for assignedDroneId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedDroneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      assignedDroneId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object assignedMissionId_ = "";
    /**
     * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
     * @return The assignedMissionId.
     */
    public java.lang.String getAssignedMissionId() {
      java.lang.Object ref = assignedMissionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignedMissionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
     * @return The bytes for assignedMissionId.
     */
    public com.google.protobuf.ByteString
        getAssignedMissionIdBytes() {
      java.lang.Object ref = assignedMissionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignedMissionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
     * @param value The assignedMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedMissionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      assignedMissionId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedMissionId() {
      assignedMissionId_ = getDefaultInstance().getAssignedMissionId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_mission_id = 9 [json_name = "assignedMissionId"];</code>
     * @param value The bytes for assignedMissionId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedMissionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      assignedMissionId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object solvingSessionId_ = "";
    /**
     * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
     * @return The solvingSessionId.
     */
    public java.lang.String getSolvingSessionId() {
      java.lang.Object ref = solvingSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        solvingSessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
     * @return The bytes for solvingSessionId.
     */
    public com.google.protobuf.ByteString
        getSolvingSessionIdBytes() {
      java.lang.Object ref = solvingSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        solvingSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
     * @param value The solvingSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSolvingSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      solvingSessionId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSolvingSessionId() {
      solvingSessionId_ = getDefaultInstance().getSolvingSessionId();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string solving_session_id = 10 [json_name = "solvingSessionId"];</code>
     * @param value The bytes for solvingSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSolvingSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      solvingSessionId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.Order)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.Order)
  private static final com.dronefleet.shared.models.Order DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.Order();
  }

  public static com.dronefleet.shared.models.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Order>
      PARSER = new com.google.protobuf.AbstractParser<Order>() {
    @java.lang.Override
    public Order parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Order> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Order> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.Order getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

