// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf enum {@code dronefleet.v1.OrderStatus}
 */
public enum OrderStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ORDER_STATUS_UNSPECIFIED = 0;</code>
   */
  ORDER_STATUS_UNSPECIFIED(0),
  /**
   * <code>ORDER_STATUS_PENDING = 1;</code>
   */
  ORDER_STATUS_PENDING(1),
  /**
   * <code>ORDER_STATUS_SOLVING = 2;</code>
   */
  ORDER_STATUS_SOLVING(2),
  /**
   * <code>ORDER_STATUS_ASSIGNED = 3;</code>
   */
  ORDER_STATUS_ASSIGNED(3),
  /**
   * <code>ORDER_STATUS_IN_DELIVERY = 4;</code>
   */
  ORDER_STATUS_IN_DELIVERY(4),
  /**
   * <code>ORDER_STATUS_DELIVERED = 5;</code>
   */
  ORDER_STATUS_DELIVERED(5),
  /**
   * <code>ORDER_STATUS_CANCELLED = 6;</code>
   */
  ORDER_STATUS_CANCELLED(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ORDER_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int ORDER_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ORDER_STATUS_PENDING = 1;</code>
   */
  public static final int ORDER_STATUS_PENDING_VALUE = 1;
  /**
   * <code>ORDER_STATUS_SOLVING = 2;</code>
   */
  public static final int ORDER_STATUS_SOLVING_VALUE = 2;
  /**
   * <code>ORDER_STATUS_ASSIGNED = 3;</code>
   */
  public static final int ORDER_STATUS_ASSIGNED_VALUE = 3;
  /**
   * <code>ORDER_STATUS_IN_DELIVERY = 4;</code>
   */
  public static final int ORDER_STATUS_IN_DELIVERY_VALUE = 4;
  /**
   * <code>ORDER_STATUS_DELIVERED = 5;</code>
   */
  public static final int ORDER_STATUS_DELIVERED_VALUE = 5;
  /**
   * <code>ORDER_STATUS_CANCELLED = 6;</code>
   */
  public static final int ORDER_STATUS_CANCELLED_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderStatus forNumber(int value) {
    switch (value) {
      case 0: return ORDER_STATUS_UNSPECIFIED;
      case 1: return ORDER_STATUS_PENDING;
      case 2: return ORDER_STATUS_SOLVING;
      case 3: return ORDER_STATUS_ASSIGNED;
      case 4: return ORDER_STATUS_IN_DELIVERY;
      case 5: return ORDER_STATUS_DELIVERED;
      case 6: return ORDER_STATUS_CANCELLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderStatus>() {
          public OrderStatus findValueByNumber(int number) {
            return OrderStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dronefleet.shared.models.CommonProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final OrderStatus[] VALUES = values();

  public static OrderStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dronefleet.v1.OrderStatus)
}

