// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/order.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031dronefleet/v1/order.proto\022\rdronefleet." +
      "v1\032\032dronefleet/v1/common.proto\032\037google/p" +
      "rotobuf/timestamp.proto\"\365\003\n\005Order\022\016\n\002id\030" +
      "\001 \001(\tR\002id\022@\n\017pickup_location\030\002 \001(\0132\027.dro" +
      "nefleet.v1.PositionR\016pickupLocation\022D\n\021d" +
      "elivery_location\030\003 \001(\0132\027.dronefleet.v1.P" +
      "ositionR\020deliveryLocation\0222\n\006status\030\004 \001(" +
      "\0162\032.dronefleet.v1.OrderStatusR\006status\0228\n" +
      "\010priority\030\005 \001(\0162\034.dronefleet.v1.OrderPri" +
      "orityR\010priority\022!\n\014product_type\030\006 \001(\tR\013p" +
      "roductType\0229\n\ncreated_at\030\007 \001(\0132\032.google." +
      "protobuf.TimestampR\tcreatedAt\022*\n\021assigne" +
      "d_drone_id\030\010 \001(\tR\017assignedDroneId\022.\n\023ass" +
      "igned_mission_id\030\t \001(\tR\021assignedMissionI" +
      "d\022,\n\022solving_session_id\030\n \001(\tR\020solvingSe" +
      "ssionIdB\177\n\034com.dronefleet.shared.modelsB" +
      "\nOrderProtoP\001\242\002\003DXX\252\002\rDronefleet.V1\312\002\rDr" +
      "onefleet\\V1\342\002\031Dronefleet\\V1\\GPBMetadata\352" +
      "\002\016Dronefleet::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dronefleet.shared.models.CommonProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_dronefleet_v1_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_Order_descriptor,
        new java.lang.String[] { "Id", "PickupLocation", "DeliveryLocation", "Status", "Priority", "ProductType", "CreatedAt", "AssignedDroneId", "AssignedMissionId", "SolvingSessionId", });
    com.dronefleet.shared.models.CommonProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
