// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dronefleet.v1.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double lat = 1 [json_name = "lat"];</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lon = 2 [json_name = "lon"];</code>
   * @return The lon.
   */
  double getLon();
}
