// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/common.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf enum {@code dronefleet.v1.ProductType}
 */
public enum ProductType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PRODUCT_TYPE_UNSPECIFIED = 0;</code>
   */
  PRODUCT_TYPE_UNSPECIFIED(0),
  /**
   * <code>PRODUCT_TYPE_MEDICINE = 1;</code>
   */
  PRODUCT_TYPE_MEDICINE(1),
  /**
   * <code>PRODUCT_TYPE_VACCINE = 2;</code>
   */
  PRODUCT_TYPE_VACCINE(2),
  /**
   * <code>PRODUCT_TYPE_BLOOD = 3;</code>
   */
  PRODUCT_TYPE_BLOOD(3),
  /**
   * <code>PRODUCT_TYPE_ORGAN = 4;</code>
   */
  PRODUCT_TYPE_ORGAN(4),
  /**
   * <code>PRODUCT_TYPE_MEDICAL_DEVICE = 5;</code>
   */
  PRODUCT_TYPE_MEDICAL_DEVICE(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PRODUCT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int PRODUCT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PRODUCT_TYPE_MEDICINE = 1;</code>
   */
  public static final int PRODUCT_TYPE_MEDICINE_VALUE = 1;
  /**
   * <code>PRODUCT_TYPE_VACCINE = 2;</code>
   */
  public static final int PRODUCT_TYPE_VACCINE_VALUE = 2;
  /**
   * <code>PRODUCT_TYPE_BLOOD = 3;</code>
   */
  public static final int PRODUCT_TYPE_BLOOD_VALUE = 3;
  /**
   * <code>PRODUCT_TYPE_ORGAN = 4;</code>
   */
  public static final int PRODUCT_TYPE_ORGAN_VALUE = 4;
  /**
   * <code>PRODUCT_TYPE_MEDICAL_DEVICE = 5;</code>
   */
  public static final int PRODUCT_TYPE_MEDICAL_DEVICE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProductType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProductType forNumber(int value) {
    switch (value) {
      case 0: return PRODUCT_TYPE_UNSPECIFIED;
      case 1: return PRODUCT_TYPE_MEDICINE;
      case 2: return PRODUCT_TYPE_VACCINE;
      case 3: return PRODUCT_TYPE_BLOOD;
      case 4: return PRODUCT_TYPE_ORGAN;
      case 5: return PRODUCT_TYPE_MEDICAL_DEVICE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProductType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProductType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProductType>() {
          public ProductType findValueByNumber(int number) {
            return ProductType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dronefleet.shared.models.CommonProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final ProductType[] VALUES = values();

  public static ProductType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProductType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dronefleet.v1.ProductType)
}

