// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/snapshot.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public final class SnapshotProto {
  private SnapshotProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dronefleet_v1_OptimizationSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dronefleet_v1_OptimizationSnapshot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034dronefleet/v1/snapshot.proto\022\rdronefle" +
      "et.v1\032\031dronefleet/v1/depot.proto\032\031dronef" +
      "leet/v1/drone.proto\032\031dronefleet/v1/order" +
      ".proto\032\035dronefleet/v1/warehouse.proto\032\037g" +
      "oogle/protobuf/timestamp.proto\"\261\002\n\024Optim" +
      "izationSnapshot\022\035\n\nsession_id\030\001 \001(\tR\tses" +
      "sionId\0228\n\ttimestamp\030\002 \001(\0132\032.google.proto" +
      "buf.TimestampR\ttimestamp\022*\n\005depot\030\003 \001(\0132" +
      "\024.dronefleet.v1.DepotR\005depot\022,\n\006drones\030\004" +
      " \003(\0132\024.dronefleet.v1.DroneR\006drones\022,\n\006or" +
      "ders\030\005 \003(\0132\024.dronefleet.v1.OrderR\006orders" +
      "\0228\n\nwarehouses\030\006 \003(\0132\030.dronefleet.v1.War" +
      "ehouseR\nwarehousesB\202\001\n\034com.dronefleet.sh" +
      "ared.modelsB\rSnapshotProtoP\001\242\002\003DXX\252\002\rDro" +
      "nefleet.V1\312\002\rDronefleet\\V1\342\002\031Dronefleet\\" +
      "V1\\GPBMetadata\352\002\016Dronefleet::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dronefleet.shared.models.DepotProto.getDescriptor(),
          com.dronefleet.shared.models.DroneProto.getDescriptor(),
          com.dronefleet.shared.models.OrderProto.getDescriptor(),
          com.dronefleet.shared.models.WarehouseProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_dronefleet_v1_OptimizationSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dronefleet_v1_OptimizationSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dronefleet_v1_OptimizationSnapshot_descriptor,
        new java.lang.String[] { "SessionId", "Timestamp", "Depot", "Drones", "Orders", "Warehouses", });
    com.dronefleet.shared.models.DepotProto.getDescriptor();
    com.dronefleet.shared.models.DroneProto.getDescriptor();
    com.dronefleet.shared.models.OrderProto.getDescriptor();
    com.dronefleet.shared.models.WarehouseProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
