// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/warehouse.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

public interface WarehouseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dronefleet.v1.Warehouse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   * @return The position.
   */
  com.dronefleet.shared.models.Position getPosition();
  /**
   * <code>.dronefleet.v1.Position position = 3 [json_name = "position"];</code>
   */
  com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder();

  /**
   * <code>repeated string authorized_product_types = 4 [json_name = "authorizedProductTypes"];</code>
   * @return A list containing the authorizedProductTypes.
   */
  java.util.List<java.lang.String>
      getAuthorizedProductTypesList();
  /**
   * <code>repeated string authorized_product_types = 4 [json_name = "authorizedProductTypes"];</code>
   * @return The count of authorizedProductTypes.
   */
  int getAuthorizedProductTypesCount();
  /**
   * <code>repeated string authorized_product_types = 4 [json_name = "authorizedProductTypes"];</code>
   * @param index The index of the element to return.
   * @return The authorizedProductTypes at the given index.
   */
  java.lang.String getAuthorizedProductTypes(int index);
  /**
   * <code>repeated string authorized_product_types = 4 [json_name = "authorizedProductTypes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the authorizedProductTypes at the given index.
   */
  com.google.protobuf.ByteString
      getAuthorizedProductTypesBytes(int index);

  /**
   * <code>bool is_cold_storage_capable = 5 [json_name = "isColdStorageCapable"];</code>
   * @return The isColdStorageCapable.
   */
  boolean getIsColdStorageCapable();
}
