// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dronefleet/v1/mission.proto

// Protobuf Java Version: 3.25.1
package com.dronefleet.shared.models;

/**
 * Protobuf type {@code dronefleet.v1.Waypoint}
 */
public final class Waypoint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dronefleet.v1.Waypoint)
    WaypointOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Waypoint.newBuilder() to construct.
  private Waypoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Waypoint() {
    type_ = 0;
    relatedOrderId_ = "";
    relatedWarehouseId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Waypoint();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Waypoint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Waypoint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dronefleet.shared.models.Waypoint.class, com.dronefleet.shared.models.Waypoint.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override public com.dronefleet.shared.models.WaypointType getType() {
    com.dronefleet.shared.models.WaypointType result = com.dronefleet.shared.models.WaypointType.forNumber(type_);
    return result == null ? com.dronefleet.shared.models.WaypointType.UNRECOGNIZED : result;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.dronefleet.shared.models.Position position_;
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  @java.lang.Override
  public com.dronefleet.shared.models.Position getPosition() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }
  /**
   * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
   */
  @java.lang.Override
  public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
  }

  public static final int RELATED_ORDER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relatedOrderId_ = "";
  /**
   * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
   * @return The relatedOrderId.
   */
  @java.lang.Override
  public java.lang.String getRelatedOrderId() {
    java.lang.Object ref = relatedOrderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relatedOrderId_ = s;
      return s;
    }
  }
  /**
   * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
   * @return The bytes for relatedOrderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelatedOrderIdBytes() {
    java.lang.Object ref = relatedOrderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relatedOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATED_WAREHOUSE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relatedWarehouseId_ = "";
  /**
   * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
   * @return The relatedWarehouseId.
   */
  @java.lang.Override
  public java.lang.String getRelatedWarehouseId() {
    java.lang.Object ref = relatedWarehouseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relatedWarehouseId_ = s;
      return s;
    }
  }
  /**
   * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
   * @return The bytes for relatedWarehouseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelatedWarehouseIdBytes() {
    java.lang.Object ref = relatedWarehouseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relatedWarehouseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.dronefleet.shared.models.WaypointType.WAYPOINT_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPosition());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relatedOrderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, relatedOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relatedWarehouseId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, relatedWarehouseId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.dronefleet.shared.models.WaypointType.WAYPOINT_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relatedOrderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, relatedOrderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relatedWarehouseId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, relatedWarehouseId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dronefleet.shared.models.Waypoint)) {
      return super.equals(obj);
    }
    com.dronefleet.shared.models.Waypoint other = (com.dronefleet.shared.models.Waypoint) obj;

    if (type_ != other.type_) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (!getRelatedOrderId()
        .equals(other.getRelatedOrderId())) return false;
    if (!getRelatedWarehouseId()
        .equals(other.getRelatedWarehouseId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (37 * hash) + RELATED_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelatedOrderId().hashCode();
    hash = (37 * hash) + RELATED_WAREHOUSE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelatedWarehouseId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dronefleet.shared.models.Waypoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dronefleet.shared.models.Waypoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dronefleet.shared.models.Waypoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dronefleet.shared.models.Waypoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dronefleet.shared.models.Waypoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dronefleet.v1.Waypoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dronefleet.v1.Waypoint)
      com.dronefleet.shared.models.WaypointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Waypoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Waypoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dronefleet.shared.models.Waypoint.class, com.dronefleet.shared.models.Waypoint.Builder.class);
    }

    // Construct using com.dronefleet.shared.models.Waypoint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      relatedOrderId_ = "";
      relatedWarehouseId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dronefleet.shared.models.MissionProto.internal_static_dronefleet_v1_Waypoint_descriptor;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Waypoint getDefaultInstanceForType() {
      return com.dronefleet.shared.models.Waypoint.getDefaultInstance();
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Waypoint build() {
      com.dronefleet.shared.models.Waypoint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dronefleet.shared.models.Waypoint buildPartial() {
      com.dronefleet.shared.models.Waypoint result = new com.dronefleet.shared.models.Waypoint(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dronefleet.shared.models.Waypoint result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.relatedOrderId_ = relatedOrderId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.relatedWarehouseId_ = relatedWarehouseId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dronefleet.shared.models.Waypoint) {
        return mergeFrom((com.dronefleet.shared.models.Waypoint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dronefleet.shared.models.Waypoint other) {
      if (other == com.dronefleet.shared.models.Waypoint.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (!other.getRelatedOrderId().isEmpty()) {
        relatedOrderId_ = other.relatedOrderId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getRelatedWarehouseId().isEmpty()) {
        relatedWarehouseId_ = other.relatedWarehouseId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              relatedOrderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              relatedWarehouseId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public com.dronefleet.shared.models.WaypointType getType() {
      com.dronefleet.shared.models.WaypointType result = com.dronefleet.shared.models.WaypointType.forNumber(type_);
      return result == null ? com.dronefleet.shared.models.WaypointType.UNRECOGNIZED : result;
    }
    /**
     * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.dronefleet.shared.models.WaypointType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.WaypointType type = 1 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.dronefleet.shared.models.Position position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> positionBuilder_;
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     * @return The position.
     */
    public com.dronefleet.shared.models.Position getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(
        com.dronefleet.shared.models.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder mergePosition(com.dronefleet.shared.models.Position value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          position_ != null &&
          position_ != com.dronefleet.shared.models.Position.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.Position.Builder getPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    public com.dronefleet.shared.models.PositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.dronefleet.shared.models.Position.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.dronefleet.v1.Position position = 2 [json_name = "position"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dronefleet.shared.models.Position, com.dronefleet.shared.models.Position.Builder, com.dronefleet.shared.models.PositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private java.lang.Object relatedOrderId_ = "";
    /**
     * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
     * @return The relatedOrderId.
     */
    public java.lang.String getRelatedOrderId() {
      java.lang.Object ref = relatedOrderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedOrderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
     * @return The bytes for relatedOrderId.
     */
    public com.google.protobuf.ByteString
        getRelatedOrderIdBytes() {
      java.lang.Object ref = relatedOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
     * @param value The relatedOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedOrderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relatedOrderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedOrderId() {
      relatedOrderId_ = getDefaultInstance().getRelatedOrderId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string related_order_id = 3 [json_name = "relatedOrderId"];</code>
     * @param value The bytes for relatedOrderId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relatedOrderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object relatedWarehouseId_ = "";
    /**
     * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
     * @return The relatedWarehouseId.
     */
    public java.lang.String getRelatedWarehouseId() {
      java.lang.Object ref = relatedWarehouseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relatedWarehouseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
     * @return The bytes for relatedWarehouseId.
     */
    public com.google.protobuf.ByteString
        getRelatedWarehouseIdBytes() {
      java.lang.Object ref = relatedWarehouseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relatedWarehouseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
     * @param value The relatedWarehouseId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedWarehouseId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relatedWarehouseId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRelatedWarehouseId() {
      relatedWarehouseId_ = getDefaultInstance().getRelatedWarehouseId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string related_warehouse_id = 4 [json_name = "relatedWarehouseId"];</code>
     * @param value The bytes for relatedWarehouseId to set.
     * @return This builder for chaining.
     */
    public Builder setRelatedWarehouseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relatedWarehouseId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dronefleet.v1.Waypoint)
  }

  // @@protoc_insertion_point(class_scope:dronefleet.v1.Waypoint)
  private static final com.dronefleet.shared.models.Waypoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dronefleet.shared.models.Waypoint();
  }

  public static com.dronefleet.shared.models.Waypoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Waypoint>
      PARSER = new com.google.protobuf.AbstractParser<Waypoint>() {
    @java.lang.Override
    public Waypoint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Waypoint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Waypoint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dronefleet.shared.models.Waypoint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

